import type { SchedulerStrings } from "../src/stringResources";

/** Compact Brazilian Portuguese labels; keep placeholders and date-name order intact. */
export const brazilianPortugueseStrings: SchedulerStrings = {
  "agendaEmpty": "Nada agendado neste período.",
  "apply": "Aplicar",
  "assignedTo": "Atribuído a",
  "unassigned": "Sem atribuição",
  "cancel": "Cancelar",
  "close": "Fechar",
  "delete": "Excluir",
  "deleteConfirmAction": "Excluir",
  "deleteConfirmCount": "Excluir {count} itens? Esta ação é irreversível.",
  "deleteConfirmMessage": "Excluir {title}? Esta ação é irreversível.",
  "deleteConfirmTitle": "Confirmar exclusão",
  "dialogFinishAfterStart": "O fim deve ser posterior ao início.",
  "directionEarlier": "Antes",
  "directionLater": "Depois",
  "dialogNameRequired": "O nome é obrigatório.",
  "dialogBestOptions": "Melhores opções",
  "dialogNotAllowed": "Esta alteração não é permitida.",
  "dialogOtherOptions": "Outras",
  "draftItem": "Novo item",
  "duration": "Duração",
  "emptyResources": "Sem recursos. Verifique a configuração da exibição.",
  "entitlementGrace": "Pagamento em atraso. Prazo até {date}",
  "entitlementLapsed": "Assinatura do Chrona expirada. Otimização e geração pausadas até regularizar o pagamento.",
  "entitlementPaused": "Otimizador pausado desde {since}. Chrona inacessível; você pode continuar agendando.",
  "entitlementPlanUsage": "Plano e uso",
  "entitlementResources": "{scheduled} de {included} recursos agendados neste período",
  "entitlementResourcesAbovePlan": "{scheduled} de {included} recursos agendados; acima do plano",
  "entitlementResourcesNoCeiling": "{scheduled} recursos agendados neste período",
  "entitlementRetry": "Tentar novamente",
  "finish": "Fim",
  "flagCauseAssigned": "atribuído",
  "flagCauseEdited": "editado",
  "flagCausePinned": "fixado",
  "flagReason": "Não é mais necessário: {required} necessários, {existing} existentes. Mantido por estar {cause}.",
  "goToDate": "Ir para data",
  "interval": "Intervalo",
  "intervalDay": "Dia",
  "itemsCount": "{count} itens",
  "intervalDaySpan": "Faixa",
  "intervalMonth": "Mês",
  "intervalWeek": "Semana",
  "legendBusyElsewhere": "Ocupado em outra tarefa",
  "legendCustom": "Destacado",
  "legendHoliday": "Feriado",
  "legendNeedsCover": "Sem cobertura",
  "legendNonWorking": "Fora do horário",
  "legendPreferred": "Horário preferido",
  "legendUnavailable": "Indisponível",
  "legendUnpreferred": "Horário não preferido",
  "menuDeleteCount": "Excluir {count} itens",
  "menuDuplicate": "Duplicar",
  "menuOpen": "Abrir",
  "menuOpenRecord": "Abrir registro",
  "menuPin": "Fixar",
  "menuPinCount": "Fixar {count} itens",
  "menuUnpin": "Desafixar",
  "menuUnpinCount": "Desafixar {count} itens",
  "menuMoveTo": "Mover para…",
  "menuMoveToCount": "Mover {count} itens para…",
  "menuReassign": "Reatribuir a…",
  "menuReassignCount": "Reatribuir {count} itens a…",
  "groupByLabel": "Agrupar linhas",
  "groupByNone": "Sem grupos",
  "ungrouped": "Sem grupo",
  "hideUnscheduledPanel": "Ocultar itens não agendados",
  "unscheduledToggle": "Não agendados ({count})",
  "conversionOptimize": "Otimizar",
  "conversionTitle": "Toda a escala, de uma só vez",
  "conversionPitchProblem": "Agendar um item de cada vez oculta as interações.",
  "conversionPitchMechanism": "Chrona considera toda a escala: competências, disponibilidade, horas, custos e conflitos.",
  "conversionInfoLead": "Opcional. Teste grátis.",
  "conversionInfoBody": "Conectar o Chrona não altera o funcionamento do agendador.",
  "conversionClaimBase": "Trabalho atribuído. Conflitos resolvidos.",
  "conversionClaimRespected": "Critérios respeitados: {list}.",
  "capabilityAssignment": "atribuições",
  "capabilityLocks": "bloqueios",
  "capabilityRoles": "funções",
  "capabilityAvailability": "disponibilidade",
  "capabilityHours": "horas",
  "capabilityCost": "custos",
  "listAnd": "e",
  "solveCapabilitiesLine": "Otimizando com: {list}",
  "conversionCountsSuffix": " — contagem local, sem envio de dados.",
  "conversionCoverageGaps": "{gaps} falhas de cobertura",
  "conversionSampleTitle": "Exemplo de otimização",
  "conversionSampleBefore": "Antes",
  "conversionSampleAfter": "Após otimizar",
  "conversionSampleCounts": "{open} itens sem atribuição · {conflicts} conflitos",
  "conversionAxisLabels": "Seg 8:00|Seg 12:00|Seg 16:00|Ter 8:00",
  "conversionSentTitle": "Dados de uma otimização real",
  "conversionSentWork": "Tarefas: horários, requisitos e ID da pessoa atribuída",
  "conversionSentPeople": "Pessoas: IDs, competências, disponibilidade, horas e custos horários",
  "conversionSentNothingElse": "Nada mais: sem nomes, notas, contatos ou registros não relacionados",
  "conversionInspect": "Ver dados exatos",
  "conversionPayloadNote": "Este JSON exato. Nada é enviado antes de conectar.",
  "conversionLockLine": "Grátis. Sem cartão. Nada é enviado antes de conectar. O exemplo nunca altera sua escala.",
  "conversionAllClear": "Sem alertas nos dados atuais. Contagem local, sem envio de dados.",
  "conversionNotNow": "Agora não",
  "conversionConnect": "Testar grátis",
  "conversionLearnMore": "Saiba mais",
  "menuAssign": "Atribuir pessoal…",
  "menuUnschedule": "Desatribuir",
  "unscheduleConfirmTitle": "Desatribuir turno",
  "unscheduleConfirmMessage": "Desatribuir {title}? O turno mantém o horário e volta para Não agendados para nova atribuição.",
  "unscheduleConfirmAction": "Desatribuir",
  "unscheduledLaneLabel": "Não agendados · {count}",
  "assignTitle": "Atribuir pessoal",
  "assignBestOptions": "Melhores opções",
  "assignNotAvailable": "Indisponível",
  "assignShowEveryone": "Ver todos ({count})",
  "assignSearchPlaceholder": "Pesquisar pessoal",
  "assignHoursLeft": "Restam {left} h de {capacity} h",
  "assignReasonUnavailable": "Indisponível {range}",
  "assignReasonBusy": "Já trabalha {range}",
  "assignReasonHours": "Excederia {capacity} h",
  "assignEmpty": "Nenhuma pessoa encontrada.",
  "assignAction": "Atribuir a {name}",
  "monthMore": "+{count} mais",
  "monthsLong": "janeiro|fevereiro|março|abril|maio|junho|julho|agosto|setembro|outubro|novembro|dezembro",
  "monthsShort": "jan|fev|mar|abr|mai|jun|jul|ago|set|out|nov|dez",
  "moveAmount": "Quantidade",
  "moveDialogTitle": "Mover para",
  "moveDirection": "Direção",
  "moveUnit": "Unidade",
  "name": "Nome",
  "needsCover": "Sem cobertura",
  "newEvent": "Novo evento",
  "next": "Próximo",
  "noticeBlocked": "Bloqueado: {reason}",
  "noticeWarning": "Nota: {reason}",
  "pinnedNotice": "Fixado. Desafixe para editar.",
  "previous": "Anterior",
  "reassignDialogTitle": "Reatribuir a",
  "periodNext": "Próximo período",
  "periodOf": "dia {day} de {days}",
  "redo": "Refazer",
  "rosterOpenShifts": "Turnos não atribuídos",
  "periodPrevious": "Período anterior",
  "proposalApply": "Aplicar",
  "proposalAppliedMany": "{count} sugestões aplicadas",
  "proposalAppliedOne": "1 sugestão aplicada",
  "proposalDiscard": "Descartar",
  "proposalEmpty": "Sem alterações propostas",
  "proposalDropped": "{count} descartados",
  "proposalDropChange": "Descartar alteração",
  "proposalKeepChange": "Manter alteração",
  "proposalKeepAll": "Manter todas",
  "proposalKeepNone": "Não manter nenhuma",
  "proposalPerPerson": "{count} alterações, resumidas por pessoa.",
  "proposalPersonShifts": "{count} turnos · {hours} h",
  "proposalPersonShiftOne": "1 turno · {hours} h",
  "proposalHeldBack": "Retidas ({count})",
  "proposalHeldBackHint": "Cada uma criaria uma dupla atribuição, por isso Aplicar não a inclui.",
  "proposalApplyAll": "Aplicar as {count}",
  "proposalApplySome": "Aplicar {kept} de {count}",
  "proposalReviewHint": "Revisando a proposta. Aplique ou descarte para editar.",
  "proposalShowCurrent": "Atual",
  "proposalShowProposed": "Proposto",
  "proposalHoldCompare": "Manter para comparar",
  "proposalChangesOnly": "Só alterações",
  "proposalPanelTitle": "Alterações propostas",
  "proposalPanelToggle": "Alterações propostas ({count})",
  "proposalGroupAssigned": "Atribuídos ({count})",
  "proposalGroupMoved": "Movidos ({count})",
  "proposalGroupUnassigned": "Sem atribuição ({count})",
  "proposalMustBroken": "Algumas regras obrigatórias violadas",
  "proposalMustKept": "Todas as regras obrigatórias cumpridas",
  "proposalWas": "antes: {detail}",
  "proposalTitle": "Escala proposta",
  "proposalSummaryChangeOne": "1 alteração",
  "proposalSummaryChanges": "{count} alterações",
  "proposalFilled": "{filled} de {total} turnos preenchidos",
  "scorecardLabel": "Em relação à escala atual",
  "scoreFilled": "Turnos preenchidos",
  "scoreMustBroken": "Regras obrigatórias violadas",
  "scoreNone": "Nenhuma",
  "scoreSome": "Algumas",
  "scoreNotChecked": "Não verificado",
  "scoreChanges": "Alterações",
  "scorePeople": "Pessoas afetadas",
  "scoreVsNow": "{delta} vs. atual",
  "scoreNoChange": "Inalterado",
  "scoreOfPeople": "de {count} pessoas",
  "scorecardToggle": "Indicadores",
  "scoreSearch": "Escalas testadas",
  "scoreSearchNote": "{better} melhorias · {seconds} s",
  "scoreSearchNoteOne": "1 melhoria · {seconds} s",
  "scoreSearchUnit": "versões",
  "proposalCheckFoundMany": "{count} alterações ficaram desatualizadas. Verifique-as e aplique novamente.",
  "proposalCheckFoundOne": "1 alteração ficou desatualizada. Verifique-a e aplique novamente.",
  "proposalDoubleBookingMany": "{count} duplas atribuições",
  "proposalDoubleBookingOne": "1 dupla atribuição",
  "proposalDoubleBooks": "Dupla atribuição de {person} com {title}",
  "proposalGroupOutOfDate": "Desatualizadas ({count})",
  "proposalOutOfDate": "{count} desatualizadas",
  "proposalReasonChanged": "Alterado depois que o plano foi criado",
  "proposalReasonNewShift": "{person} agora tem outro turno neste horário",
  "proposalReasonPersonChanged": "Os dados de {person} mudaram depois que o plano foi criado",
  "proposalReasonStarted": "Já começou",
  "proposalReasonUnavailable": "{person} agora está indisponível neste horário",
  "solvePeriodPassed": "Este período já passou",
  "solveQueued": "Na fila…",
  "solveElapsed": "{seconds} s",
  "requiredSkills": "Competências exigidas",
  "resizeResources": "Redimensionar coluna de recursos",
  "resizeUnscheduled": "Redimensionar painel de não agendados",
  "resourceHeader": "Recurso",
  "save": "Salvar",
  "savedViews": "Exibições",
  "start": "Início",
  "solve": "Otimizar",
  "solveFailed": "Falha na otimização: {message}",
  "solveQuotaRemaining": "Restam {remaining} de {limit} otimizações grátis hoje",
  "solveQuotaExhausted": "As otimizações grátis de hoje acabaram. Volte amanhã ou mude de plano para uso ilimitado.",
  "solveQuotaUpgrade": "Mudar de plano",
  "resumeFinished": "Uma otimização terminou na sua ausência.",
  "resumeRunning": "Uma otimização desta escala está em andamento.",
  "resumeChanged": "Uma otimização terminou na sua ausência, mas a escala mudou. O resultado não se aplica mais.",
  "resumeReview": "Revisar",
  "resumeFollow": "Acompanhar",
  "resumeDiscard": "Descartar",
  "openChronaAccount": "Abrir conta Chrona",
  "solveSolving": "Otimizando…",
  "timeScale": "Escala temporal",
  "timeScaleLeast": "{count} minutos: menos espaço para detalhes",
  "timeScaleMinutes": "{count} minutos",
  "timeScaleMost": "{count} minutos: mais espaço para detalhes",
  "timeScaleShort": "{count} min",
  "timeZoneChip": "Fuso horário visível",
  "timelineLabel": "Linha do tempo de recursos",
  "today": "Hoje",
  "undo": "Desfazer",
  "unitDays": "Dias",
  "unitHours": "Horas",
  "unitWeeks": "Semanas",
  "unscheduledAll": "Todos",
  "unscheduledEmpty": "Tudo preenchido.",
  "unscheduledEmptyInView": "Nada neste período.",
  "unscheduledFilterLabel": "Filtrar itens não agendados",
  "unscheduledInView": "Na exibição",
  "unscheduledTitle": "Não agendados",
  "weekdaysShort": "dom|seg|ter|qua|qui|sex|sáb",
  "nextMonth": "Próximo mês",
  "previousMonth": "Mês anterior",
  "schedulerSettings": "Configurações do agendador",
  "fullScreen": "Tela cheia",
  "fullScreenExit": "Sair da tela cheia",
  "weekdaysLong": "domingo|segunda-feira|terça-feira|quarta-feira|quinta-feira|sexta-feira|sábado",
  "noDate": "Sem data",
  "scoreNotCounted": "Não contado desta vez",
  "mustBreakdownTitle": "Regras obrigatórias",
  "mustRowRest": "Descanso entre turnos",
  "mustRowDaysInARow": "Dias seguidos",
  "mustRowSkills": "Competências",
  "mustRowOnLeave": "Ausente ou indisponível",
  "mustRowOther": "Outras regras obrigatórias",
  "mustKindOverlap": "Dupla atribuição",
  "mustKindMaximumHours": "Horas máx.",
  "mustKindSplitParts": "Turno dividido",
  "mustKindUnlisted": "Outras",
  "mustRowSummary": "{rule}: {now} agora, {proposed} na proposta",
  "mustRowOpen": "{rule}: {now} agora, {proposed} na proposta. Mostrar turnos",
  "mustUncheckedOne": "Não verificado para 1 pessoa",
  "mustUnchecked": "Não verificado para {count} pessoas",
  "mustNoAgreementOne": "1 pessoa não tem acordo: descanso e limites de dias não verificados.",
  "mustNoAgreement": "{count} pessoas não têm acordo: descanso e limites de dias não verificados.",
  "mustNoAgreementNobody": "Ninguém tem acordo: descanso e limites de dias não verificados.",
  "proposalMustKeptUncheckedOne": "Regras obrigatórias cumpridas · não verificado para 1 pessoa",
  "proposalMustKeptUnchecked": "Regras obrigatórias cumpridas · não verificado para {count} pessoas",
  "drillGroup": "{rule} ({count})",
  "drillMore": "e mais {count}",
  "reasonFixesRest": "Corrige o descanso de {name} ({hours} h)",
  "reasonFixesDaysInARow": "Corrige os dias seguidos de {name}",
  "reasonFixesSkill": "Corrige uma competência que faltava",
  "reasonFixesMust": "Corrige uma regra obrigatória violada",
  "reasonAddsRest": "Cria um descanso curto para {name} ({hours} h)",
  "reasonAddsMust": "Viola uma regra obrigatória",
  "reasonUnpreferred": "{name} prefere não trabalhar nesse horário",
  "reasonAvoidsUnpreferred": "Evita o horário não preferido de {name}",
  "reasonFillsOpen": "Preenche um turno não atribuído",
  "reasonPersonFixesOne": "Corrige 1 violação",
  "reasonPersonFixes": "Corrige {count} violações",
  "countsOnlyNote": "Escala grande: só contagens. Os motivos não são exibidos.",
  "tryAgain": "Tentar novamente",
  "menuWhyNot": "Por que não…?",
  "whyNotPerson": "Pessoa",
  "whyNotPlaceholder": "Digite um nome",
  "whyNotNoMatch": "Nenhum resultado",
  "whyNotNow": "agora {name}",
  "whyNotChecking": "Verificando {name}…",
  "whyNotVerdictMustOne": "{name} violaria 1 regra obrigatória",
  "whyNotVerdictMust": "{name} violaria {count} regras obrigatórias",
  "whyNotVerdictShould": "{name} cumpre todas as regras obrigatórias, mas se encaixa pior",
  "whyNotVerdictEqual": "{name} se encaixa igualmente bem.",
  "whyNotVerdictEqualReview": "{name} se encaixa igualmente bem. A otimização teve que escolher.",
  "whyNotVerdictBetter": "{name} se encaixa melhor.",
  "whyNotTakingOff": "{name} perde o turno",
  "whyNotPrefers": "{name} prefere trabalhar nesse horário",
  "ruleSpreadOfShifts": "Distribuição de turnos",
  "ruleMinimumHours": "Horas mínimas",
  "whyNotLessEven": "{rule}: menos equilibrada",
  "whyNotMoreEven": "{rule}: mais equilibrada",
  "whyNotWorse": "{rule}: pior",
  "whyNotBetter": "{rule}: melhor",
  "whyNotNoAgreement": "{name} não tem acordo: descanso e limites de dias não verificados.",
  "whyNotUnavailable": "Não foi possível verificar agora",
  "whyNotRetryIn": "Não foi possível verificar agora. Tente novamente em {seconds} s.",
  "whyNotRosterChanged": "A escala mudou.",
  "whyNotAskAgain": "Perguntar novamente",
  "whyNotAssign": "Atribuir a {name}",
  "whyNotSwap": "Trocar {name} e {other}",
  "whyNotTakes": "{name} fica com {shift}",
  "whyNotLeftOpen": "{shift} de {name} ficaria sem atribuição",
  "whyNotInReview": "Para usar {name}, descarte esta alteração e aja depois de Aplicar.",
  "scorePreferences": "Preferências atendidas",
  "scorePreferencesValue": "{met} de {total}",
  "scorePreferencesNone": "Nenhuma preferência registrada",
  "preferencesUnmetTitle": "Preferências não atendidas"
};
