import type { SchedulerStrings } from "../src/stringResources";

/** Compact dutch labels; keep placeholders and date-name order intact. */
export const dutchStrings: SchedulerStrings = {
  "agendaEmpty": "Niets gepland in deze periode.",
  "apply": "Toepassen",
  "assignedTo": "Toegewezen aan",
  "unassigned": "Niet toegewezen",
  "cancel": "Annuleren",
  "close": "Sluiten",
  "delete": "Verwijderen",
  "deleteConfirmAction": "Verwijderen",
  "deleteConfirmCount": "{count} items verwijderen? Dit kan niet ongedaan worden gemaakt.",
  "deleteConfirmMessage": "{title} verwijderen? Dit kan niet ongedaan worden gemaakt.",
  "deleteConfirmTitle": "Verwijderen bevestigen",
  "dialogFinishAfterStart": "Het einde moet na het begin liggen.",
  "directionEarlier": "Eerder",
  "directionLater": "Later",
  "dialogNameRequired": "Naam is verplicht.",
  "dialogBestOptions": "Beste opties",
  "dialogNotAllowed": "Deze wijziging is niet toegestaan.",
  "dialogOtherOptions": "Overige",
  "draftItem": "Nieuw item",
  "duration": "Duur",
  "emptyResources": "Geen resources. Controleer de instellingen van de weergave.",
  "entitlementGrace": "Betaling te laat. Uitstel tot {date}",
  "entitlementLapsed": "Chrona-abonnement verlopen. Optimaliseren en genereren zijn gepauzeerd tot de betaling is geregeld.",
  "entitlementPaused": "Optimalisatie gepauzeerd sinds {since}. Chrona is onbereikbaar; plannen blijft werken.",
  "entitlementPlanUsage": "Abonnement en gebruik",
  "entitlementResources": "{scheduled} van {included} resources gepland deze periode",
  "entitlementResourcesAbovePlan": "{scheduled} van {included} resources gepland, boven abonnement",
  "entitlementResourcesNoCeiling": "{scheduled} resources gepland deze periode",
  "entitlementRetry": "Opnieuw",
  "finish": "Einde",
  "flagCauseAssigned": "toegewezen",
  "flagCauseEdited": "bewerkt",
  "flagCausePinned": "vastgezet",
  "flagReason": "Niet meer nodig: {required} vereist, {existing} aanwezig. Behouden: {cause}.",
  "goToDate": "Ga naar datum",
  "interval": "Interval",
  "intervalDay": "Dag",
  "itemsCount": "{count} items",
  "intervalDaySpan": "Tijdvak",
  "intervalMonth": "Maand",
  "intervalWeek": "Week",
  "legendBusyElsewhere": "Elders bezet",
  "legendCustom": "Gemarkeerd",
  "legendHoliday": "Feestdag",
  "legendNeedsCover": "Bezetting nodig",
  "legendNonWorking": "Buiten werktijd",
  "legendPreferred": "Voorkeurstijden",
  "legendUnavailable": "Niet beschikbaar",
  "legendUnpreferred": "Niet-voorkeurstijden",
  "menuDeleteCount": "{count} items verwijderen",
  "menuDuplicate": "Dupliceren",
  "menuOpen": "Openen",
  "menuOpenRecord": "Record openen",
  "menuPin": "Vastzetten",
  "menuPinCount": "{count} items vastzetten",
  "menuUnpin": "Losmaken",
  "menuUnpinCount": "{count} items losmaken",
  "menuMoveTo": "Verplaatsen naar…",
  "menuMoveToCount": "{count} items verplaatsen naar…",
  "menuReassign": "Opnieuw toewijzen…",
  "menuReassignCount": "{count} items opnieuw toewijzen…",
  "groupByLabel": "Rijen groeperen",
  "groupByNone": "Geen groepering",
  "ungrouped": "Niet gegroepeerd",
  "hideUnscheduledPanel": "Ongeplande items verbergen",
  "unscheduledToggle": "Ongepland ({count})",
  "conversionOptimize": "Optimaliseren",
  "conversionTitle": "Het hele rooster in één keer",
  "conversionPitchProblem": "Eén item tegelijk plannen mist de samenhang.",
  "conversionPitchMechanism": "Chrona bekijkt het hele rooster: vaardigheden, beschikbaarheid, uren, kosten en conflicten.",
  "conversionInfoLead": "Optioneel. Gratis proberen.",
  "conversionInfoBody": "Chrona koppelen verandert niets aan de planner.",
  "conversionClaimBase": "Werk toegewezen. Conflicten opgelost.",
  "conversionClaimRespected": "Rekening gehouden met: {list}.",
  "capabilityAssignment": "toewijzing",
  "capabilityLocks": "vergrendelingen",
  "capabilityRoles": "rollen",
  "capabilityAvailability": "beschikbaarheid",
  "capabilityHours": "uren",
  "capabilityCost": "kosten",
  "listAnd": "en",
  "solveCapabilitiesLine": "Optimaliseren met: {list}",
  "conversionCountsSuffix": " — lokaal geteld, niets verzonden.",
  "conversionCoverageGaps": "{gaps} bezettingsgaten",
  "conversionSampleTitle": "Voorbeeldoptimalisatie",
  "conversionSampleBefore": "Voor",
  "conversionSampleAfter": "Na optimalisatie",
  "conversionSampleCounts": "{open} open items · {conflicts} conflicten",
  "conversionAxisLabels": "Ma 8:00|Ma 12:00|Ma 16:00|Di 8:00",
  "conversionSentTitle": "Gegevens voor een echte optimalisatie",
  "conversionSentWork": "Werkitems: tijden, vereisten en ID van de toegewezen persoon",
  "conversionSentPeople": "Personen: resource-ID's, vaardigheden, beschikbaarheid, uren en tarieven",
  "conversionSentNothingElse": "Niets anders: geen namen, notities, contactgegevens of overige records",
  "conversionInspect": "Exacte gegevens bekijken",
  "conversionPayloadNote": "Exact deze JSON. Niets wordt verzonden vóór het koppelen.",
  "conversionLockLine": "Gratis. Geen creditcard. Niets verzonden vóór het koppelen. Een voorbeeld wijzigt nooit je rooster.",
  "conversionAllClear": "Geen meldingen in de huidige gegevens. Lokaal geteld, niets verzonden.",
  "conversionNotNow": "Niet nu",
  "conversionConnect": "Gratis proberen",
  "conversionLearnMore": "Meer informatie",
  "menuAssign": "Personeel toewijzen…",
  "menuUnschedule": "Toewijzing wissen",
  "unscheduleConfirmTitle": "Diensttoewijzing wissen",
  "unscheduleConfirmMessage": "Toewijzing van {title} wissen? De dienst behoudt zijn tijd en keert terug naar Ongepland voor nieuwe toewijzing.",
  "unscheduleConfirmAction": "Toewijzing wissen",
  "unscheduledLaneLabel": "Ongepland · {count}",
  "assignTitle": "Personeel toewijzen",
  "assignBestOptions": "Beste opties",
  "assignNotAvailable": "Niet beschikbaar",
  "assignShowEveryone": "Iedereen ({count})",
  "assignSearchPlaceholder": "Personeel zoeken",
  "assignHoursLeft": "{left} u over van {capacity} u",
  "assignReasonUnavailable": "Niet beschikbaar {range}",
  "assignReasonBusy": "Werkt al {range}",
  "assignReasonHours": "Zou {capacity} u overschrijden",
  "assignEmpty": "Geen passend personeel.",
  "assignAction": "{name} toewijzen",
  "monthMore": "+{count} meer",
  "monthsLong": "januari|februari|maart|april|mei|juni|juli|augustus|september|oktober|november|december",
  "monthsShort": "jan|feb|mrt|apr|mei|jun|jul|aug|sep|okt|nov|dec",
  "moveAmount": "Aantal",
  "moveDialogTitle": "Verplaatsen naar",
  "moveDirection": "Richting",
  "moveUnit": "Eenheid",
  "name": "Naam",
  "needsCover": "Bezetting nodig",
  "newEvent": "Nieuwe afspraak",
  "next": "Volgende",
  "noticeBlocked": "Geblokkeerd: {reason}",
  "noticeWarning": "Let op: {reason}",
  "pinnedNotice": "Vastgezet. Maak los om te wijzigen.",
  "previous": "Vorige",
  "reassignDialogTitle": "Opnieuw toewijzen",
  "periodNext": "Volgende periode",
  "periodOf": "dag {day} van {days}",
  "redo": "Opnieuw uitvoeren",
  "rosterOpenShifts": "Open diensten",
  "periodPrevious": "Vorige periode",
  "proposalApply": "Toepassen",
  "proposalAppliedMany": "{count} voorstellen toegepast",
  "proposalAppliedOne": "1 voorstel toegepast",
  "proposalDiscard": "Verwerpen",
  "proposalEmpty": "Geen wijzigingen voorgesteld",
  "proposalDropped": "{count} verworpen",
  "proposalDropChange": "Wijziging verwerpen",
  "proposalKeepChange": "Wijziging behouden",
  "proposalKeepAll": "Alles behouden",
  "proposalKeepNone": "Niets behouden",
  "proposalPerPerson": "{count} wijzigingen, per persoon samengevat.",
  "proposalPersonShifts": "{count} diensten · {hours} u",
  "proposalPersonShiftOne": "1 dienst · {hours} u",
  "proposalHeldBack": "Tegengehouden ({count})",
  "proposalHeldBackHint": "Elk zou iemand dubbel boeken, dus Toepassen laat het weg.",
  "proposalApplyAll": "Alle {count} toepassen",
  "proposalApplySome": "{kept} van {count} toepassen",
  "proposalReviewHint": "Voorstel bekijken. Pas toe of verwerp om te bewerken.",
  "proposalShowCurrent": "Huidig",
  "proposalShowProposed": "Voorgesteld",
  "proposalHoldCompare": "Vasthouden om te vergelijken",
  "proposalChangesOnly": "Alleen wijzigingen",
  "proposalPanelTitle": "Voorgestelde wijzigingen",
  "proposalPanelToggle": "Voorgestelde wijzigingen ({count})",
  "proposalGroupAssigned": "Toegewezen ({count})",
  "proposalGroupMoved": "Verplaatst ({count})",
  "proposalGroupUnassigned": "Niet toegewezen ({count})",
  "proposalMustBroken": "Enkele verplichte regels overtreden",
  "proposalMustKept": "Alle verplichte regels nageleefd",
  "proposalWas": "was {detail}",
  "proposalTitle": "Voorgesteld rooster",
  "proposalSummaryChangeOne": "1 wijziging",
  "proposalSummaryChanges": "{count} wijzigingen",
  "proposalFilled": "{filled} van {total} diensten bezet",
  "scorecardLabel": "Ten opzichte van het huidige rooster",
  "scoreFilled": "Bezette diensten",
  "scoreMustBroken": "Overtreden verplichte regels",
  "scoreNone": "Geen",
  "scoreSome": "Enkele",
  "scoreNotChecked": "Niet gecontroleerd",
  "scoreChanges": "Wijzigingen",
  "scorePeople": "Betrokken personen",
  "scoreVsNow": "{delta} t.o.v. nu",
  "scoreNoChange": "Ongewijzigd",
  "scoreOfPeople": "van {count} personen",
  "scorecardToggle": "Kerncijfers",
  "scoreSearch": "Geteste roosters",
  "scoreSearchNote": "{better} verbeteringen · {seconds} s",
  "scoreSearchNoteOne": "1 verbetering · {seconds} s",
  "scoreSearchUnit": "versies",
  "proposalCheckFoundMany": "{count} wijzigingen zijn verouderd. Controleer ze en pas opnieuw toe.",
  "proposalCheckFoundOne": "1 wijziging is verouderd. Controleer deze en pas opnieuw toe.",
  "proposalDoubleBookingMany": "{count} dubbele boekingen",
  "proposalDoubleBookingOne": "1 dubbele boeking",
  "proposalDoubleBooks": "Dubbele boeking van {person} met {title}",
  "proposalGroupOutOfDate": "Verouderd ({count})",
  "proposalOutOfDate": "{count} verouderd",
  "proposalReasonChanged": "Gewijzigd nadat het plan is gemaakt",
  "proposalReasonNewShift": "{person} heeft nu een andere dienst op dit tijdstip",
  "proposalReasonPersonChanged": "Gegevens van {person} gewijzigd nadat het plan is gemaakt",
  "proposalReasonStarted": "Al begonnen",
  "proposalReasonUnavailable": "{person} is nu niet beschikbaar op dit tijdstip",
  "solvePeriodPassed": "Deze periode is voorbij",
  "solveQueued": "In wachtrij…",
  "solveElapsed": "{seconds} s",
  "requiredSkills": "Vereiste vaardigheden",
  "resizeResources": "Resourcekolom vergroten of verkleinen",
  "resizeUnscheduled": "Paneel Ongepland vergroten of verkleinen",
  "resourceHeader": "Resource",
  "save": "Opslaan",
  "savedViews": "Weergaven",
  "start": "Begin",
  "solve": "Optimaliseren",
  "solveFailed": "Optimalisatie mislukt: {message}",
  "solveQuotaRemaining": "Vandaag {remaining} van {limit} gratis optimalisaties over",
  "solveQuotaExhausted": "Gratis optimalisaties voor vandaag op. Morgen zijn er meer, of upgrade voor onbeperkt gebruik.",
  "solveQuotaUpgrade": "Upgraden",
  "resumeFinished": "Een optimalisatie is afgerond tijdens je afwezigheid.",
  "resumeRunning": "Er loopt een optimalisatie voor dit rooster.",
  "resumeChanged": "Een optimalisatie is afgerond tijdens je afwezigheid, maar het rooster is gewijzigd. Het resultaat is niet meer toepasbaar.",
  "resumeReview": "Bekijken",
  "resumeFollow": "Volgen",
  "resumeDiscard": "Verwerpen",
  "openChronaAccount": "Chrona-account openen",
  "solveSolving": "Optimaliseren…",
  "timeScale": "Tijdschaal",
  "timeScaleLeast": "{count} minuten – minste ruimte voor details",
  "timeScaleMinutes": "{count} minuten",
  "timeScaleMost": "{count} minuten – meeste ruimte voor details",
  "timeScaleShort": "{count} min",
  "timeZoneChip": "Getoonde tijdzone",
  "timelineLabel": "Resourcetijdlijn",
  "today": "Vandaag",
  "undo": "Ongedaan maken",
  "unitDays": "Dagen",
  "unitHours": "Uren",
  "unitWeeks": "Weken",
  "unscheduledAll": "Alles",
  "unscheduledEmpty": "Alles bezet.",
  "unscheduledEmptyInView": "Niets in deze periode.",
  "unscheduledFilterLabel": "Ongeplande items filteren",
  "unscheduledInView": "In weergave",
  "unscheduledTitle": "Ongepland",
  "weekdaysShort": "zo|ma|di|wo|do|vr|za",
  "nextMonth": "Volgende maand",
  "previousMonth": "Vorige maand",
  "schedulerSettings": "Plannerinstellingen",
  "fullScreen": "Volledig scherm",
  "fullScreenExit": "Volledig scherm sluiten",
  "weekdaysLong": "zondag|maandag|dinsdag|woensdag|donderdag|vrijdag|zaterdag",
  "noDate": "Geen datum"
};
