import type { SchedulerStrings } from "../src/stringResources";

/** Compact french labels; keep placeholders and date-name order intact. */
export const frenchStrings: SchedulerStrings = {
  "agendaEmpty": "Rien de prévu sur cette période.",
  "apply": "Appliquer",
  "assignedTo": "Affecté à",
  "unassigned": "Non affecté",
  "cancel": "Annuler",
  "close": "Fermer",
  "delete": "Supprimer",
  "deleteConfirmAction": "Supprimer",
  "deleteConfirmCount": "Supprimer {count} éléments ? Cette action est irréversible.",
  "deleteConfirmMessage": "Supprimer {title} ? Cette action est irréversible.",
  "deleteConfirmTitle": "Confirmer la suppression",
  "dialogFinishAfterStart": "La fin doit suivre le début.",
  "directionEarlier": "Plus tôt",
  "directionLater": "Plus tard",
  "dialogNameRequired": "Le nom est requis.",
  "dialogBestOptions": "Meilleurs choix",
  "dialogNotAllowed": "Cette modification est interdite.",
  "dialogOtherOptions": "Autres",
  "draftItem": "Nouvel élément",
  "duration": "Durée",
  "emptyResources": "Aucune ressource. Vérifiez la configuration de la vue.",
  "entitlementGrace": "Paiement en retard. Délai jusqu'au {date}",
  "entitlementLapsed": "Abonnement Chrona expiré. Optimisation et génération suspendues jusqu'à régularisation du paiement.",
  "entitlementPaused": "Optimisation suspendue depuis {since}. Chrona est inaccessible. Le planning reste utilisable.",
  "entitlementPlanUsage": "Offre et usage",
  "entitlementResources": "{scheduled} ressources sur {included} planifiées cette période",
  "entitlementResourcesAbovePlan": "{scheduled} ressources sur {included} planifiées, offre dépassée",
  "entitlementResourcesNoCeiling": "{scheduled} ressources planifiées cette période",
  "entitlementRetry": "Réessayer",
  "finish": "Fin",
  "flagCauseAssigned": "affecté",
  "flagCauseEdited": "modifié",
  "flagCausePinned": "épinglé",
  "flagReason": "Superflu : {required} requis, {existing} existants. Conservé car {cause}.",
  "goToDate": "Aller à la date",
  "interval": "Intervalle",
  "intervalDay": "Jour",
  "itemsCount": "{count} éléments",
  "intervalDaySpan": "Plage",
  "intervalMonth": "Mois",
  "intervalWeek": "Semaine",
  "legendBusyElsewhere": "Occupé ailleurs",
  "legendCustom": "Surligné",
  "legendHoliday": "Jour férié",
  "legendNeedsCover": "À pourvoir",
  "legendNonWorking": "Hors travail",
  "legendPreferred": "Heures préférées",
  "legendUnavailable": "Indisponible",
  "legendUnpreferred": "Heures non préférées",
  "menuDeleteCount": "Supprimer {count} éléments",
  "menuDuplicate": "Dupliquer",
  "menuOpen": "Ouvrir",
  "menuOpenRecord": "Ouvrir la fiche",
  "menuPin": "Épingler",
  "menuPinCount": "Épingler {count} éléments",
  "menuUnpin": "Détacher",
  "menuUnpinCount": "Détacher {count} éléments",
  "menuMoveTo": "Déplacer vers…",
  "menuMoveToCount": "Déplacer {count} éléments vers…",
  "menuReassign": "Réaffecter à…",
  "menuReassignCount": "Réaffecter {count} éléments à…",
  "groupByLabel": "Grouper les lignes",
  "groupByNone": "Sans groupe",
  "ungrouped": "Sans groupe",
  "hideUnscheduledPanel": "Masquer les éléments non planifiés",
  "unscheduledToggle": "Non planifiés ({count})",
  "conversionOptimize": "Optimiser",
  "conversionTitle": "Tout le planning, optimisé en une fois",
  "conversionPitchProblem": "Planifier un élément à la fois masque les interactions.",
  "conversionPitchMechanism": "Chrona optimise tout le planning : compétences, disponibilités, heures, coûts et conflits.",
  "conversionInfoLead": "Facultatif. Essai gratuit.",
  "conversionInfoBody": "Connecter Chrona ne change pas le fonctionnement du planning.",
  "conversionClaimBase": "Travail affecté. Conflits résolus.",
  "conversionClaimRespected": "Critères respectés : {list}.",
  "capabilityAssignment": "affectations",
  "capabilityLocks": "verrouillages",
  "capabilityRoles": "rôles",
  "capabilityAvailability": "disponibilités",
  "capabilityHours": "heures",
  "capabilityCost": "coûts",
  "listAnd": "et",
  "solveCapabilitiesLine": "Optimisation selon : {list}",
  "conversionCountsSuffix": " — comptage local, aucun envoi.",
  "conversionCoverageGaps": "{gaps} manques de couverture",
  "conversionSampleTitle": "Exemple d'optimisation",
  "conversionSampleBefore": "Avant",
  "conversionSampleAfter": "Après optimisation",
  "conversionSampleCounts": "{open} éléments à pourvoir · {conflicts} conflits",
  "conversionAxisLabels": "Lun 8 h|Lun 12 h|Lun 16 h|Mar 8 h",
  "conversionSentTitle": "Données d'une vraie optimisation",
  "conversionSentWork": "Tâches : horaires, exigences, ID de la personne affectée",
  "conversionSentPeople": "Personnes : ID, compétences, disponibilités, heures et tarifs",
  "conversionSentNothingElse": "Rien d'autre : ni noms, notes, coordonnées ou fiches sans rapport",
  "conversionInspect": "Voir les données exactes",
  "conversionPayloadNote": "Ce JSON exact. Aucun envoi avant connexion.",
  "conversionLockLine": "Gratuit. Sans carte bancaire. Aucun envoi avant connexion. L'exemple ne modifie jamais votre planning.",
  "conversionAllClear": "Aucun problème signalé dans les données actuelles. Comptage local, aucun envoi.",
  "conversionNotNow": "Plus tard",
  "conversionConnect": "Essayer gratuitement",
  "conversionLearnMore": "En savoir plus",
  "menuAssign": "Affecter…",
  "menuUnschedule": "Désaffecter",
  "unscheduleConfirmTitle": "Désaffecter le poste",
  "unscheduleConfirmMessage": "Désaffecter {title} ? Le poste garde ses horaires et revient aux éléments non planifiés.",
  "unscheduleConfirmAction": "Désaffecter",
  "unscheduledLaneLabel": "Non planifiés · {count}",
  "assignTitle": "Affecter le personnel",
  "assignBestOptions": "Meilleurs choix",
  "assignNotAvailable": "Indisponible",
  "assignShowEveryone": "Voir tous ({count})",
  "assignSearchPlaceholder": "Rechercher une personne",
  "assignHoursLeft": "{left} h libres sur {capacity} h",
  "assignReasonUnavailable": "Indisponible {range}",
  "assignReasonBusy": "Déjà occupé {range}",
  "assignReasonHours": "Dépasserait {capacity} h",
  "assignEmpty": "Aucune personne trouvée.",
  "assignAction": "Affecter {name}",
  "monthMore": "+{count} autres",
  "monthsLong": "janvier|février|mars|avril|mai|juin|juillet|août|septembre|octobre|novembre|décembre",
  "monthsShort": "janv.|févr.|mars|avr.|mai|juin|juil.|août|sept.|oct.|nov.|déc.",
  "moveAmount": "Nombre",
  "moveDialogTitle": "Déplacer vers",
  "moveDirection": "Sens",
  "moveUnit": "Unité",
  "name": "Nom",
  "needsCover": "À pourvoir",
  "newEvent": "Nouvel événement",
  "next": "Suivant",
  "noticeBlocked": "Bloqué : {reason}",
  "noticeWarning": "Note : {reason}",
  "pinnedNotice": "Épinglé. Détachez pour modifier.",
  "previous": "Précédent",
  "reassignDialogTitle": "Réaffecter à",
  "periodNext": "Période suivante",
  "periodOf": "jour {day} sur {days}",
  "redo": "Rétablir",
  "rosterOpenShifts": "Postes à pourvoir",
  "periodPrevious": "Période précédente",
  "proposalApply": "Appliquer",
  "proposalAppliedMany": "{count} suggestions appliquées",
  "proposalAppliedOne": "1 suggestion appliquée",
  "proposalDiscard": "Rejeter",
  "proposalEmpty": "Aucune modification proposée",
  "proposalDropped": "{count} écartés",
  "proposalDropChange": "Écarter ce changement",
  "proposalKeepChange": "Garder ce changement",
  "proposalKeepAll": "Tout garder",
  "proposalKeepNone": "Ne rien garder",
  "proposalPerPerson": "{count} modifications, résumées par personne.",
  "proposalPersonShifts": "{count} postes · {hours} h",
  "proposalPersonShiftOne": "1 poste · {hours} h",
  "proposalHeldBack": "Retenus ({count})",
  "proposalHeldBackHint": "Chacun créerait une double affectation : Appliquer l'écarte.",
  "proposalApplyAll": "Appliquer les {count}",
  "proposalApplySome": "Appliquer {kept} sur {count}",
  "proposalReviewHint": "Proposition en cours. Appliquez ou rejetez pour modifier.",
  "proposalShowCurrent": "Actuel",
  "proposalShowProposed": "Proposé",
  "proposalHoldCompare": "Maintenir pour comparer",
  "proposalChangesOnly": "Modifications seules",
  "proposalPanelTitle": "Modifications proposées",
  "proposalPanelToggle": "Modifications proposées ({count})",
  "proposalGroupAssigned": "Affectés ({count})",
  "proposalGroupMoved": "Déplacés ({count})",
  "proposalGroupUnassigned": "Non affectés ({count})",
  "proposalMustBroken": "Certaines règles impératives enfreintes",
  "proposalMustKept": "Toutes les règles impératives respectées",
  "proposalWas": "avant : {detail}",
  "proposalTitle": "Planning proposé",
  "proposalSummaryChangeOne": "1 modification",
  "proposalSummaryChanges": "{count} modifications",
  "proposalFilled": "{filled} postes pourvus sur {total}",
  "scorecardLabel": "Par rapport au planning actuel",
  "scoreFilled": "Postes pourvus",
  "scoreMustBroken": "Règles impératives enfreintes",
  "scoreNone": "Aucune",
  "scoreSome": "Certaines",
  "scoreNotChecked": "Non vérifié",
  "scoreChanges": "Modifications",
  "scorePeople": "Personnes concernées",
  "scoreVsNow": "{delta} vs actuel",
  "scoreNoChange": "Inchangé",
  "scoreOfPeople": "sur {count} personnes",
  "scorecardToggle": "Indicateurs",
  "scoreSearch": "Plannings testés",
  "scoreSearchNote": "{better} améliorations · {seconds} s",
  "scoreSearchNoteOne": "1 amélioration · {seconds} s",
  "scoreSearchUnit": "versions",
  "proposalCheckFoundMany": "{count} modifications sont devenues obsolètes. Vérifiez-les, puis appliquez à nouveau.",
  "proposalCheckFoundOne": "1 modification est devenue obsolète. Vérifiez-la, puis appliquez à nouveau.",
  "proposalDoubleBookingMany": "{count} doubles affectations",
  "proposalDoubleBookingOne": "1 double affectation",
  "proposalDoubleBooks": "Double affectation de {person} avec {title}",
  "proposalGroupOutOfDate": "Obsolètes ({count})",
  "proposalOutOfDate": "{count} obsolètes",
  "proposalReasonChanged": "Modifié après la création du plan",
  "proposalReasonNewShift": "{person} a maintenant un autre poste à cette heure",
  "proposalReasonPersonChanged": "Les informations de {person} ont changé après la création du plan",
  "proposalReasonStarted": "Déjà commencé",
  "proposalReasonUnavailable": "{person} est maintenant indisponible à cette heure",
  "solvePeriodPassed": "Cette période est passée",
  "solveQueued": "En attente…",
  "solveElapsed": "{seconds} s",
  "requiredSkills": "Compétences requises",
  "resizeResources": "Redimensionner la colonne des ressources",
  "resizeUnscheduled": "Redimensionner le panneau non planifié",
  "resourceHeader": "Ressource",
  "save": "Enregistrer",
  "savedViews": "Vues",
  "start": "Début",
  "solve": "Optimiser",
  "solveFailed": "Échec de l'optimisation : {message}",
  "solveQuotaRemaining": "{remaining} optimisations gratuites sur {limit} restantes aujourd'hui",
  "solveQuotaExhausted": "Quota gratuit du jour épuisé. Revenez demain ou changez d'offre pour un usage illimité.",
  "solveQuotaUpgrade": "Changer d'offre",
  "resumeFinished": "Une optimisation s'est terminée en votre absence.",
  "resumeRunning": "Une optimisation est en cours pour ce planning.",
  "resumeChanged": "Une optimisation s'est terminée en votre absence, mais le planning a changé. Son résultat n'est plus applicable.",
  "resumeReview": "Examiner",
  "resumeFollow": "Suivre",
  "resumeDiscard": "Rejeter",
  "openChronaAccount": "Ouvrir le compte Chrona",
  "solveSolving": "Optimisation…",
  "timeScale": "Échelle horaire",
  "timeScaleLeast": "{count} minutes – moins de détails",
  "timeScaleMinutes": "{count} minutes",
  "timeScaleMost": "{count} minutes – plus de détails",
  "timeScaleShort": "{count} min",
  "timeZoneChip": "Fuseau affiché",
  "timelineLabel": "Chronologie des ressources",
  "today": "Aujourd'hui",
  "undo": "Annuler",
  "unitDays": "Jours",
  "unitHours": "Heures",
  "unitWeeks": "Semaines",
  "unscheduledAll": "Tous",
  "unscheduledEmpty": "Tout est couvert.",
  "unscheduledEmptyInView": "Rien sur cette période.",
  "unscheduledFilterLabel": "Filtrer les éléments non planifiés",
  "unscheduledInView": "Dans la vue",
  "unscheduledTitle": "Non planifiés",
  "weekdaysShort": "dim.|lun.|mar.|mer.|jeu.|ven.|sam.",
  "nextMonth": "Mois suivant",
  "previousMonth": "Mois précédent",
  "schedulerSettings": "Paramètres du planning",
  "fullScreen": "Plein écran",
  "fullScreenExit": "Quitter le plein écran",
  "weekdaysLong": "dimanche|lundi|mardi|mercredi|jeudi|vendredi|samedi",
  "noDate": "Sans date",
  "scoreNotCounted": "Non compté cette fois",
  "mustBreakdownTitle": "Règles impératives",
  "mustRowRest": "Repos entre postes",
  "mustRowDaysInARow": "Jours consécutifs",
  "mustRowSkills": "Compétences",
  "mustRowOnLeave": "En congé ou indisponible",
  "mustRowOther": "Autres règles impératives",
  "mustKindOverlap": "Double affectation",
  "mustKindMaximumHours": "Heures max.",
  "mustKindSplitParts": "Service fractionné",
  "mustKindUnlisted": "Autres",
  "mustRowSummary": "{rule} : {now} maintenant, {proposed} proposé",
  "mustRowOpen": "{rule} : {now} maintenant, {proposed} proposé. Afficher les postes",
  "mustUncheckedOne": "Non vérifié pour 1 personne",
  "mustUnchecked": "Non vérifié pour {count} personnes",
  "mustNoAgreementOne": "1 personne n'a pas d'accord : repos et limites de jours non vérifiés.",
  "mustNoAgreement": "{count} personnes n'ont pas d'accord : repos et limites de jours non vérifiés.",
  "mustNoAgreementNobody": "Personne n'a d'accord : repos et limites de jours non vérifiés.",
  "proposalMustKeptUncheckedOne": "Règles impératives respectées · non vérifié pour 1 personne",
  "proposalMustKeptUnchecked": "Règles impératives respectées · non vérifié pour {count} personnes",
  "drillGroup": "{rule} ({count})",
  "drillMore": "et {count} autres",
  "reasonFixesRest": "Corrige le repos de {name} ({hours} h)",
  "reasonFixesDaysInARow": "Corrige les jours consécutifs de {name}",
  "reasonFixesSkill": "Corrige une compétence manquante",
  "reasonFixesMust": "Corrige une règle impérative enfreinte",
  "reasonAddsRest": "Crée un repos court pour {name} ({hours} h)",
  "reasonAddsMust": "Enfreint une règle impérative",
  "reasonUnpreferred": "{name} préfère ne pas travailler à ce moment",
  "reasonAvoidsUnpreferred": "Évite les heures non préférées de {name}",
  "reasonFillsOpen": "Affecte un poste à pourvoir",
  "reasonPersonFixesOne": "Corrige 1 règle enfreinte",
  "reasonPersonFixes": "Corrige {count} règles enfreintes",
  "countsOnlyNote": "Planning volumineux : comptes seulement. Les raisons ne s'affichent pas.",
  "tryAgain": "Réessayer",
  "menuWhyNot": "Pourquoi pas… ?",
  "whyNotPerson": "Personne",
  "whyNotPlaceholder": "Saisissez un nom",
  "whyNotNoMatch": "Aucun résultat",
  "whyNotNow": "actuellement {name}",
  "whyNotChecking": "Vérification de {name}…",
  "whyNotVerdictMustOne": "{name} enfreindrait 1 règle impérative",
  "whyNotVerdictMust": "{name} enfreindrait {count} règles impératives",
  "whyNotVerdictShould": "{name} respecte toutes les règles impératives mais convient moins bien",
  "whyNotVerdictEqual": "{name} convient aussi bien.",
  "whyNotVerdictEqualReview": "{name} convient aussi bien. L'optimisation a dû choisir.",
  "whyNotVerdictBetter": "{name} convient mieux.",
  "whyNotTakingOff": "{name} perd le poste",
  "whyNotPrefers": "{name} préfère travailler à ce moment",
  "ruleSpreadOfShifts": "Répartition des postes",
  "ruleMinimumHours": "Heures minimales",
  "whyNotLessEven": "{rule} : moins équilibrée",
  "whyNotMoreEven": "{rule} : plus équilibrée",
  "whyNotWorse": "{rule} : moins bien",
  "whyNotBetter": "{rule} : mieux",
  "whyNotNoAgreement": "{name} n'a pas d'accord : repos et limites de jours non vérifiés.",
  "whyNotUnavailable": "Vérification impossible pour l'instant",
  "whyNotRetryIn": "Vérification impossible pour l'instant. Réessayez dans {seconds} s.",
  "whyNotRosterChanged": "Le planning a changé.",
  "whyNotAskAgain": "Redemander",
  "whyNotAssign": "Affecter {name}",
  "whyNotSwap": "Échanger {name} et {other}",
  "whyNotTakes": "{name} prend {shift}",
  "whyNotLeftOpen": "{shift} de {name} resterait à pourvoir",
  "whyNotInReview": "Pour {name}, écartez ce changement et agissez après Appliquer.",
  "scorePreferences": "Préférences respectées",
  "scorePreferencesValue": "{met} sur {total}",
  "scorePreferencesNone": "Aucune préférence saisie",
  "preferencesUnmetTitle": "Préférences non respectées"
};
