import type { SchedulerStrings } from "../src/stringResources";

/** Compact french labels; keep placeholders and date-name order intact. */
export const frenchStrings: SchedulerStrings = {
  "agendaEmpty": "Rien de prévu sur cette période.",
  "apply": "Appliquer",
  "assignedTo": "Affecté à",
  "unassigned": "Non affecté",
  "bandBusyElsewhere": "Occupé ailleurs",
  "bandPreferred": "Préféré",
  "bandUnavailable": "Indisponible",
  "bandUnpreferred": "Non préféré",
  "cancel": "Annuler",
  "close": "Fermer",
  "delete": "Supprimer",
  "deleteConfirmAction": "Supprimer",
  "deleteConfirmCount": "Supprimer {count} éléments ? Cette action est irréversible.",
  "deleteConfirmMessage": "Supprimer {title} ? Cette action est irréversible.",
  "deleteConfirmTitle": "Confirmer la suppression",
  "dialogFinishAfterStart": "La fin doit suivre le début.",
  "changesSinceMany": "{count} modifications depuis",
  "changesSinceNone": "Aucune modification depuis",
  "changesSinceOne": "{count} modification depuis",
  "coverage": "Couverture",
  "currentRosterLabel": "Planning actuel",
  "directionEarlier": "Plus tôt",
  "directionLater": "Plus tard",
  "dialogNameRequired": "Le nom est requis.",
  "dialogBestOptions": "Meilleurs choix",
  "dialogNotAllowed": "Cette modification est interdite.",
  "dialogOtherOptions": "Autres",
  "draftItem": "Nouvel élément",
  "duration": "Durée",
  "emptyResources": "Aucune ressource. Vérifiez la configuration de la vue.",
  "entitlementGrace": "Paiement en retard. Délai jusqu'au {date}",
  "entitlementLapsed": "Abonnement Chrona expiré. Optimisation et génération suspendues jusqu'à régularisation du paiement.",
  "entitlementPaused": "Optimisation suspendue depuis {since}. Chrona est inaccessible. Le planning reste utilisable.",
  "entitlementPlanUsage": "Offre et usage",
  "entitlementResources": "{scheduled} ressources sur {included} planifiées cette période",
  "entitlementResourcesAbovePlan": "{scheduled} ressources sur {included} planifiées, offre dépassée",
  "entitlementResourcesNoCeiling": "{scheduled} ressources planifiées cette période",
  "entitlementRetry": "Réessayer",
  "finish": "Fin",
  "flagCauseAssigned": "affecté",
  "flagCauseEdited": "modifié",
  "flagCausePinned": "épinglé",
  "flagReason": "Superflu : {required} requis, {existing} existants. Conservé car {cause}.",
  "goToDate": "Aller à la date",
  "horizonFull": "Impossible d'ajouter un planning à cet horizon.",
  "horizonHeader": "Horizon {range} ({days} jours)",
  "interval": "Intervalle",
  "intervalDay": "Jour",
  "itemsCount": "{count} éléments",
  "intervalDaySpan": "Plage",
  "intervalMonth": "Mois",
  "intervalWeek": "Semaine",
  "legendBusyElsewhere": "Occupé ailleurs",
  "legendCustom": "Surligné",
  "legendHoliday": "Jour férié",
  "legendNeedsCover": "À pourvoir",
  "legendNonWorking": "Hors travail",
  "legendPreferred": "Heures préférées",
  "legendUnavailable": "Indisponible",
  "legendUnpreferred": "Heures non préférées",
  "menuDeleteCount": "Supprimer {count} éléments",
  "menuDuplicate": "Dupliquer",
  "menuOpen": "Ouvrir",
  "menuOpenRecord": "Ouvrir la fiche",
  "menuPin": "Épingler",
  "menuPinCount": "Épingler {count} éléments",
  "menuUnpin": "Détacher",
  "menuUnpinCount": "Détacher {count} éléments",
  "menuMoveTo": "Déplacer vers…",
  "menuMoveToCount": "Déplacer {count} éléments vers…",
  "menuReassign": "Réaffecter à…",
  "menuReassignCount": "Réaffecter {count} éléments à…",
  "groupByLabel": "Grouper les lignes",
  "groupByNone": "Sans groupe",
  "ungrouped": "Sans groupe",
  "hideUnscheduledPanel": "Masquer les éléments non planifiés",
  "unscheduledToggle": "Non planifiés ({count})",
  "conversionOptimize": "Optimiser",
  "conversionTitle": "Tout le planning, optimisé en une fois",
  "conversionPitchProblem": "Planifier un élément à la fois masque les interactions.",
  "conversionPitchMechanism": "Chrona optimise tout le planning : compétences, disponibilités, heures, coûts et conflits.",
  "conversionInfoLead": "Facultatif. Essai gratuit.",
  "conversionInfoBody": "Connecter Chrona ne change pas le fonctionnement du planning.",
  "conversionClaimBase": "Travail affecté. Conflits résolus.",
  "conversionClaimRespected": "Critères respectés : {list}.",
  "capabilityAssignment": "affectations",
  "capabilityLocks": "verrouillages",
  "capabilityRoles": "rôles",
  "capabilityAvailability": "disponibilités",
  "capabilityHours": "heures",
  "capabilityCost": "coûts",
  "listAnd": "et",
  "solveCapabilitiesLine": "Optimisation selon : {list}",
  "generate": "Générer",
  "generateWindowTitle": "Générer depuis les modèles",
  "generateWindowIntro": "Crée les éléments à pourvoir sur cette période. Relancer supprime le surplus intact et conserve les éléments modifiés ou affectés en les signalant.",
  "generateWindowFrom": "Du",
  "generateWindowTo": "Au",
  "generateWindowAction": "Générer",
  "conversionCountsSuffix": " — comptage local, aucun envoi.",
  "conversionCoverageGaps": "{gaps} manques de couverture",
  "conversionSampleTitle": "Exemple d'optimisation",
  "conversionSampleBefore": "Avant",
  "conversionSampleAfter": "Après optimisation",
  "conversionSampleCounts": "{open} éléments à pourvoir · {conflicts} conflits",
  "conversionAxisLabels": "Lun 8 h|Lun 12 h|Lun 16 h|Mar 8 h",
  "conversionSentTitle": "Données d'une vraie optimisation",
  "conversionSentWork": "Tâches : horaires, exigences, ID de la personne affectée",
  "conversionSentPeople": "Personnes : ID, compétences, disponibilités, heures et tarifs",
  "conversionSentNothingElse": "Rien d'autre : ni noms, notes, coordonnées ou fiches sans rapport",
  "conversionInspect": "Voir les données exactes",
  "conversionPayloadNote": "Ce JSON exact. Aucun envoi avant connexion.",
  "conversionLockLine": "Gratuit. Sans carte bancaire. Aucun envoi avant connexion. L'exemple ne modifie jamais votre planning.",
  "conversionAllClear": "Aucun problème signalé dans les données actuelles. Comptage local, aucun envoi.",
  "conversionNotNow": "Plus tard",
  "conversionConnect": "Essayer gratuitement",
  "conversionLearnMore": "En savoir plus",
  "menuAssign": "Affecter…",
  "menuUnschedule": "Désaffecter",
  "unscheduleConfirmTitle": "Désaffecter le poste",
  "unscheduleConfirmMessage": "Désaffecter {title} ? Le poste garde ses horaires et revient aux éléments non planifiés.",
  "unscheduleConfirmAction": "Désaffecter",
  "unscheduledLaneLabel": "Non planifiés · {count}",
  "assignTitle": "Affecter le personnel",
  "assignBestOptions": "Meilleurs choix",
  "assignNotAvailable": "Indisponible",
  "assignShowEveryone": "Voir tous ({count})",
  "assignSearchPlaceholder": "Rechercher une personne",
  "assignHoursLeft": "{left} h libres sur {capacity} h",
  "assignReasonMissingSkill": "Compétence manquante : {tag}",
  "assignReasonUnavailable": "Indisponible {range}",
  "assignReasonBusy": "Déjà occupé {range}",
  "assignReasonHours": "Dépasserait {capacity} h",
  "assignEmpty": "Aucune personne trouvée.",
  "assignAction": "Affecter {name}",
  "monthMore": "+{count} autres",
  "monthsLong": "janvier|février|mars|avril|mai|juin|juillet|août|septembre|octobre|novembre|décembre",
  "monthsShort": "janv.|févr.|mars|avr.|mai|juin|juil.|août|sept.|oct.|nov.|déc.",
  "moveAmount": "Nombre",
  "moveDialogTitle": "Déplacer vers",
  "moveDirection": "Sens",
  "moveUnit": "Unité",
  "name": "Nom",
  "needsCover": "À pourvoir",
  "newEvent": "Nouvel événement",
  "next": "Suivant",
  "optionMissingSkills": "manque {skills}",
  "optionSkillMismatch": "{count}/{total} compétences manquantes",
  "noticeBlocked": "Bloqué : {reason}",
  "noticeWarning": "Note : {reason}",
  "pinnedNotice": "Épinglé. Détachez pour modifier.",
  "previous": "Précédent",
  "reassignDialogTitle": "Réaffecter à",
  "modeOperate": "Gérer",
  "modePlan": "Planifier",
  "optimizePeriod": "Optimiser ce planning",
  "periodNext": "Période suivante",
  "periodOf": "jour {day} sur {days}",
  "planningPeriodLabel": "Période de planning",
  "publishAction": "Publier",
  "publishBlockedSequential": "Publiez d'abord le planning précédent.",
  "publishConfirmMessage": "Publier {range} ? Le personnel verra ce planning. Les modifications ultérieures seront suivies.",
  "publishConfirmTitle": "Publier le planning",
  "publishByLine": "À publier avant le {date}",
  "publishOverdueDay": "{days} jour de retard",
  "publishOverdueDays": "{days} jours de retard",
  "publishedLine": "Publié le {date}",
  "railAddRoster": "Ajouter un planning",
  "railLabel": "Horizon de planning",
  "railScrollBack": "Défiler en arrière",
  "railScrollForward": "Défiler en avant",
  "redo": "Rétablir",
  "rosterActions": "Actions du planning",
  "rosterCardLabel": "Planning {range}",
  "rosterDeleteConfirmMessage": "Supprimer {range} ? Les postes générés non affectés seront supprimés. Les postes affectés resteront.",
  "rosterDeleteConfirmTitle": "Supprimer le planning",
  "rosterDeleted": "Planning {range} supprimé : {count} postes ouverts retirés",
  "rosterGenerate": "Générer les postes",
  "rosterProgressFull": "Tout est planifié",
  "rosterProgressNotStarted": "Non commencé",
  "rosterPercentScheduled": "{percent} % planifié",
  "scopeNotice": "Rien ne change hors de ce planning.",
  "statusDraft": "Brouillon",
  "statusLocked": "Verrouillé",
  "statusPublished": "Publié",
  "periodPrevious": "Période précédente",
  "proposalApply": "Appliquer",
  "proposalAppliedMany": "{count} suggestions appliquées",
  "proposalAppliedOne": "1 suggestion appliquée",
  "proposalBlocked": "{count} bloqués",
  "proposalChanges": "{count} modifications proposées",
  "proposalNotes": "{count} notes",
  "proposalDiscard": "Rejeter",
  "proposalEmpty": "Aucune modification proposée",
  "proposalChangeOne": "1 modification proposée",
  "proposalDropped": "{count} écartés",
  "proposalDropChange": "Écarter ce changement",
  "proposalKeepChange": "Garder ce changement",
  "proposalReviewHint": "Proposition en cours. Appliquez ou rejetez pour modifier.",
  "proposalShowCurrent": "Actuel",
  "proposalShowProposed": "Proposé",
  "proposalPanelTitle": "Modifications proposées",
  "proposalGroupAssigned": "Affectés ({count})",
  "proposalGroupMoved": "Déplacés ({count})",
  "proposalGroupBlocked": "Bloqués ({count})",
  "proposalGroupUnassigned": "Non affectés ({count})",
  "proposalMustBroken": "Certaines règles impératives enfreintes",
  "proposalMustKept": "Toutes les règles impératives respectées",
  "proposalOpenMany": "{count} postes ouverts",
  "proposalOpenOne": "1 poste ouvert",
  "proposalWas": "avant : {detail}",
  "solveQueued": "En attente…",
  "solveElapsed": "{seconds} s",
  "requiredSkills": "Compétences requises",
  "resizeResources": "Redimensionner la colonne des ressources",
  "resizeUnscheduled": "Redimensionner le panneau non planifié",
  "resourceHeader": "Ressource",
  "save": "Enregistrer",
  "savedViews": "Vues",
  "start": "Début",
  "solve": "Optimiser",
  "solveFailed": "Échec de l'optimisation : {message}",
  "solveQuotaRemaining": "{remaining} optimisations gratuites sur {limit} restantes aujourd'hui",
  "solveQuotaExhausted": "Quota gratuit du jour épuisé. Revenez demain ou changez d'offre pour un usage illimité.",
  "solveQuotaUpgrade": "Changer d'offre",
  "resumeFinished": "Une optimisation s'est terminée en votre absence.",
  "resumeRunning": "Une optimisation est en cours pour ce planning.",
  "resumeChanged": "Une optimisation s'est terminée en votre absence, mais le planning a changé. Son résultat n'est plus applicable.",
  "resumeReview": "Examiner",
  "resumeFollow": "Suivre",
  "resumeDiscard": "Rejeter",
  "openChronaAccount": "Ouvrir le compte Chrona",
  "solveSolving": "Optimisation…",
  "timeScale": "Échelle horaire",
  "timeScaleLeast": "{count} minutes – moins de détails",
  "timeScaleMinutes": "{count} minutes",
  "timeScaleMost": "{count} minutes – plus de détails",
  "timeScaleShort": "{count} min",
  "timeZoneChip": "Fuseau affiché",
  "timelineLabel": "Chronologie des ressources",
  "today": "Aujourd'hui",
  "undo": "Annuler",
  "unpublishAction": "Dépublier",
  "unpublishBlockedSequential": "Dépubliez d'abord le planning suivant.",
  "unpublishConfirmMessage": "Dépublier {range} ? Le planning redevient un brouillon. L'historique de publication est conservé pour audit.",
  "unpublishConfirmTitle": "Dépublier le planning",
  "unitDays": "Jours",
  "unitHours": "Heures",
  "unitWeeks": "Semaines",
  "unscheduledAll": "Tous",
  "unscheduledEmpty": "Tout est couvert.",
  "unscheduledEmptyInView": "Rien sur cette période.",
  "unscheduledFilterLabel": "Filtrer les éléments non planifiés",
  "unscheduledInView": "Dans la vue",
  "unscheduledTitle": "Non planifiés",
  "weekdaysShort": "dim.|lun.|mar.|mer.|jeu.|ven.|sam.",
  "nextMonth": "Mois suivant",
  "previousMonth": "Mois précédent",
  "schedulerSettings": "Paramètres du planning",
  "weekdaysLong": "dimanche|lundi|mardi|mercredi|jeudi|vendredi|samedi",
  "noDate": "Sans date"
};
