/**
 * The COMPLETE German bundle for the harness locale switch, typed
 * as full SchedulerStrings on purpose: adding a string key without
 * a German translation breaks this build, so the bundle cannot rot
 * into a partial again (Matt 2026-08-24). The PCF adapter feeds
 * resx resources through the same prop in production.
 */
import type { SchedulerStrings } from "../src/stringResources";

export const germanStrings: SchedulerStrings = {
  agendaEmpty: "In diesem Zeitraum ist nichts geplant.",
  apply: "Übernehmen",
  assignedTo: "Zugewiesen an",
  unassigned: "Nicht zugewiesen",
  cancel: "Abbrechen",
  close: "Schließen",
  delete: "Löschen",
  deleteConfirmAction: "Löschen",
  deleteConfirmCount:
    "{count} Elemente löschen? Dies kann nicht rückgängig gemacht werden.",
  deleteConfirmMessage:
    "{title} löschen? Dies kann nicht rückgängig gemacht werden.",
  deleteConfirmTitle: "Löschen bestätigen",
  dialogBestOptions: "Beste Optionen",
  dialogFinishAfterStart: "Ende muss nach dem Beginn liegen.",
  dialogNameRequired: "Name ist erforderlich.",
  dialogNotAllowed: "Diese Änderung ist nicht zulässig.",
  dialogOtherOptions: "Andere",
  directionEarlier: "Früher",
  directionLater: "Später",
  draftItem: "Neues Element",
  duration: "Dauer",
  emptyResources:
    "Keine Ressourcen vorhanden. Konfiguration der Ansicht prüfen.",
  entitlementGrace: "Zahlung überfällig, Kulanzfrist bis {date}",
  entitlementLapsed: "Chrona-Abonnement abgelaufen. Optimieren und Generieren sind pausiert, bis die Abrechnung geklärt ist.",
  entitlementPaused: "Optimierer pausiert seit {since}. Chrona ist nicht erreichbar; die Planung arbeitet wie gewohnt.",
  entitlementPlanUsage: "Plan und Nutzung",
  entitlementResources: "{scheduled} von {included} Ressourcen in diesem Zeitraum geplant",
  entitlementResourcesAbovePlan: "{scheduled} von {included} Ressourcen geplant, über dem Plan",
  entitlementResourcesNoCeiling: "{scheduled} Ressourcen in diesem Zeitraum geplant",
  entitlementRetry: "Erneut versuchen",
  finish: "Ende",
  flagCauseAssigned: "zugewiesen",
  flagCauseEdited: "bearbeitet",
  flagCausePinned: "angeheftet",
  flagReason:
    "Vom Bedarf nicht mehr benötigt: {required} benötigt, {existing} vorhanden. Behalten, weil es {cause} ist.",
  goToDate: "Zu Datum springen",
  interval: "Intervall",
  intervalDay: "Tag",
  intervalDaySpan: "Zeitspanne",
  intervalMonth: "Monat",
  intervalWeek: "Woche",
  itemsCount: "{count} Elemente",
  legendBusyElsewhere: "Anderweitig im Dienst",
  legendCustom: "Hervorgehoben",
  legendHoliday: "Feiertag",
  legendNeedsCover: "Besetzung offen",
  legendNonWorking: "Arbeitsfreie Zeit",
  legendPreferred: "Bevorzugte Zeiten",
  legendUnavailable: "Nicht verfügbar",
  legendUnpreferred: "Ungünstige Zeiten",
  menuDeleteCount: "{count} Elemente löschen",
  menuDuplicate: "Duplizieren",
  menuMoveTo: "Verschieben nach...",
  menuMoveToCount: "{count} Elemente verschieben nach...",
  menuOpen: "Öffnen",
  menuOpenRecord: "Datensatz öffnen",
  menuPin: "Anheften",
  menuPinCount: "{count} Elemente anheften",
  menuReassign: "Neu zuweisen an...",
  menuReassignCount: "{count} Elemente neu zuweisen an...",
  menuUnpin: "Lösen",
  menuUnpinCount: "{count} Elemente lösen",
  groupByLabel: "Zeilen gruppieren",
  groupByNone: "Keine Gruppierung",
  ungrouped: "Ohne Gruppe",
  hideUnscheduledPanel: "Ungeplant-Bereich ausblenden",
  unscheduledToggle: "Ungeplant ({count})",
  conversionOptimize: "Optimieren",
  conversionTitle: "Der ganze Plan, in einem Zug gel\u00f6st",
  conversionPitchProblem:
    "Wer Eintrag f\u00fcr Eintrag plant, \u00fcbersieht die Wechselwirkungen.",
  conversionPitchMechanism:
    "Chrona betrachtet den ganzen Plan auf einmal \u2014 F\u00e4higkeiten, Verf\u00fcgbarkeit, Stunden, Kosten und Konflikte.",
  conversionInfoLead: "Optional. Kostenlos testen.",
  conversionInfoBody:
    "Die Verbindung mit Chrona \u00e4ndert nichts daran, wie dieser Planer funktioniert.",
  conversionClaimBase: "Offene Arbeit besetzt. Konflikte gel\u00f6st.",
  conversionClaimRespected: "{list} ber\u00fccksichtigt.",
  capabilityAssignment: "Zuweisung",
  capabilityLocks: "Sperren",
  capabilityRoles: "Rollen",
  capabilityAvailability: "Verf\u00fcgbarkeit",
  capabilityHours: "Stunden",
  capabilityCost: "Kosten",
  listAnd: "und",
  solveCapabilitiesLine: "Optimiert mit: {list}",
  conversionCountsSuffix: " \u2014 lokal gez\u00e4hlt, nichts gesendet.",
  conversionCoverageGaps: "{gaps} Abdeckungsl\u00fccken",
  conversionSampleTitle: "Ein Beispiellauf",
  conversionSampleBefore: "Vorher",
  conversionSampleAfter: "Nachher: das optimierte Ergebnis",
  conversionSampleCounts: "{open} offene Eintr\u00e4ge \u00b7 {conflicts} Konflikte",
  conversionAxisLabels: "Mo 8:00|Mo 12:00|Mo 16:00|Di 8:00",
  conversionSentTitle: "Was ein echter Lauf verwenden w\u00fcrde",
  conversionSentWork:
    "Arbeitseintr\u00e4ge \u2014 Zeiten, Anforderungen, aktuelle Zuweisung als ID",
  conversionSentPeople:
    "Personen \u2014 Ressourcen-IDs, F\u00e4higkeiten, Verf\u00fcgbarkeitsfenster, Stunden und Kostens\u00e4tze",
  conversionSentNothingElse:
    "Sonst nichts \u2014 keine Namen, keine Notizen, keine Kontaktdaten, keine fremden Datens\u00e4tze",
  conversionInspect: "Die exakten Daten pr\u00fcfen",
  conversionPayloadNote: "Genau dieses JSON. Nichts wird gesendet, bis Sie verbinden.",
  conversionLockLine:
    "Kostenlos. Keine Kreditkarte. Nichts wird gesendet, bis Sie verbinden. Ein Beispiellauf \u00e4ndert nie Ihren Zeitplan.",
  conversionAllClear:
    "In den aktuellen Daten ist nichts markiert \u2014 lokal gez\u00e4hlt, nichts gesendet.",
  conversionNotNow: "Nicht jetzt",
  conversionConnect: "Kostenlosen Beispiellauf starten",
  conversionLearnMore: "Mehr erfahren",
  menuAssign: "Personal zuweisen\u2026",
  unscheduleConfirmTitle: "Zuweisung aufheben",
  unscheduleConfirmMessage:
    "Zuweisung von {title} aufheben? Die Schicht beh\u00e4lt ihre Zeit und kehrt zur Neuzuweisung in \u201eUngeplant\u201c zur\u00fcck.",
  unscheduleConfirmAction: "Aufheben",
  unscheduledLaneLabel: "Ungeplant \u00b7 {count}",
  assignTitle: "Personal zuweisen",
  assignBestOptions: "Beste Optionen",
  assignNotAvailable: "Nicht verf\u00fcgbar",
  assignShowEveryone: "Alle anzeigen ({count})",
  assignSearchPlaceholder: "Personal suchen",
  assignHoursLeft: "{left} von {capacity} Std. frei",
  assignReasonUnavailable: "Nicht verf\u00fcgbar {range}",
  assignReasonBusy: "Bereits im Dienst {range}",
  assignReasonHours: "W\u00fcrde {capacity} Std. \u00fcberschreiten",
  assignEmpty: "Kein passendes Personal.",
  assignAction: "{name} zuweisen",
  menuUnschedule: "Zuweisung aufheben",
  monthMore: "+{count} weitere",
  monthsLong: "Januar|Februar|März|April|Mai|Juni|Juli|August|September|Oktober|November|Dezember",
  monthsShort: "Jan|Feb|Mär|Apr|Mai|Jun|Jul|Aug|Sep|Okt|Nov|Dez",
  moveAmount: "Anzahl",
  moveDialogTitle: "Verschieben nach",
  moveDirection: "Richtung",
  moveUnit: "Einheit",
  name: "Name",
  needsCover: "Besetzung offen",
  newEvent: "Neuer Termin",
  next: "Weiter",
  noticeBlocked: "Blockiert: {reason}",
  noticeWarning: "Hinweis: {reason}",
  periodNext: "Nächster Zeitraum",
  periodOf: "Tag {day} von {days}",
  periodPrevious: "Vorheriger Zeitraum",
  pinnedNotice: "Angeheftet - zum Ändern lösen.",
  previous: "Zurück",
  proposalAppliedMany: "{count} Vorschläge übernommen",
  proposalAppliedOne: "1 Vorschlag übernommen",
  proposalApply: "Übernehmen",
  proposalDiscard: "Verwerfen",
  proposalEmpty: "Keine Änderungen vorgeschlagen",
  proposalDropped: "{count} ausgelassen",
  proposalDropChange: "Änderung auslassen",
  proposalKeepChange: "Änderung behalten",
  proposalKeepAll: "Alle behalten",
  proposalKeepNone: "Keine behalten",
  proposalPerPerson: "{count} Änderungen, je Person zusammengefasst.",
  proposalPersonShifts: "{count} Schichten · {hours} Std.",
  proposalPersonShiftOne: "1 Schicht · {hours} Std.",
  proposalHeldBack: "Zurückgehalten ({count})",
  proposalHeldBackHint: "Jede ergäbe eine Doppelbuchung, darum lässt Übernehmen sie aus.",
  proposalApplyAll: "Alle {count} übernehmen",
  proposalApplySome: "{kept} von {count} übernehmen",
  proposalReviewHint: "Vorschlag in Prüfung. Übernehmen oder verwerfen, um zu bearbeiten.",
  proposalShowCurrent: "Aktuell",
  proposalShowProposed: "Vorschlag",
  proposalHoldCompare: "Zum Vergleich halten",
  proposalChangesOnly: "Nur Änderungen",
  proposalPanelTitle: "Vorgeschlagene Änderungen",
  proposalPanelToggle: "Vorgeschlagene Änderungen ({count})",
  proposalGroupAssigned: "Zugewiesen ({count})",
  proposalGroupMoved: "Verschoben ({count})",
  proposalGroupUnassigned: "Nicht zugewiesen ({count})",
  proposalMustBroken: "Einige Muss-Regeln verletzt",
  proposalMustKept: "Alle Muss-Regeln eingehalten",
  proposalWas: "vorher {detail}",
  proposalTitle: "Dienstplan-Vorschlag",
  proposalSummaryChangeOne: "1 Änderung",
  proposalSummaryChanges: "{count} Änderungen",
  proposalFilled: "{filled} von {total} Schichten besetzt",
  scorecardLabel: "Gegenüber dem aktuellen Dienstplan",
  scoreFilled: "Besetzte Schichten",
  scoreMustBroken: "Verletzte Muss-Regeln",
  scoreNone: "Keine",
  scoreSome: "Einige",
  scoreNotChecked: "Nicht geprüft",
  scoreChanges: "Änderungen",
  scorePeople: "Betroffene Personen",
  scoreVsNow: "{delta} ggü. aktuell",
  scoreNoChange: "Unverändert",
  scoreOfPeople: "von {count} Personen",
  scorecardToggle: "Kennzahlen",
  scoreSearch: "Geprüfte Dienstpläne",
  scoreSearchNote: "{better} Verbesserungen · {seconds} s",
  scoreSearchNoteOne: "1 Verbesserung · {seconds} s",
  scoreSearchUnit: "Versionen",
  proposalCheckFoundMany: "{count} Änderungen sind veraltet. Prüfen und erneut übernehmen.",
  proposalCheckFoundOne: "1 Änderung ist veraltet. Prüfen und erneut übernehmen.",
  proposalDoubleBookingMany: "{count} Doppelbuchungen",
  proposalDoubleBookingOne: "1 Doppelbuchung",
  proposalDoubleBooks: "Doppelbuchung von {person} mit {title}",
  proposalGroupOutOfDate: "Veraltet ({count})",
  proposalOutOfDate: "{count} veraltet",
  proposalReasonChanged: "Nach Erstellung des Plans geändert",
  proposalReasonNewShift: "{person} hat jetzt eine andere Schicht zu dieser Zeit",
  proposalReasonPersonChanged: "Daten von {person} nach Erstellung des Plans geändert",
  proposalReasonStarted: "Bereits begonnen",
  proposalReasonUnavailable: "{person} ist zu dieser Zeit jetzt nicht verfügbar",
  solvePeriodPassed: "Dieser Zeitraum ist vorbei",
  solveQueued: "In der Warteschlange...",
  solveElapsed: "{seconds} s",
  redo: "Wiederholen",
  rosterOpenShifts: "Offene Schichten",
  reassignDialogTitle: "Neu zuweisen an",
  requiredSkills: "Fähigkeiten",
  resizeResources: "Ressourcenspalte anpassen",
  resizeUnscheduled: "Ungeplant-Bereich anpassen",
  resourceHeader: "Ressource",
  save: "Speichern",
  savedViews: "Ansichten",
  solve: "Optimieren",
  solveFailed: "Optimierung fehlgeschlagen: {message}",
  solveQuotaRemaining: "{remaining} von {limit} kostenlosen Optimierungen heute übrig",
  solveQuotaExhausted:
    "Die kostenlosen Optimierungen für heute sind aufgebraucht. Morgen gibt es mehr — oder upgraden Sie für unbegrenzte Läufe.",
  solveQuotaUpgrade: "Upgrade",
  resumeFinished: "Eine Optimierung wurde abgeschlossen, während Sie weg waren.",
  resumeRunning: "Für diesen Plan läuft gerade eine Optimierung.",
  resumeChanged:
    "Eine Optimierung wurde abgeschlossen, während Sie weg waren, aber der Plan hat sich seitdem geändert. Das Ergebnis passt nicht mehr.",
  resumeReview: "Ansehen",
  resumeFollow: "Verfolgen",
  resumeDiscard: "Verwerfen",
  openChronaAccount: "Chrona-Konto öffnen",
  solveSolving: "Wird optimiert...",
  start: "Beginn",
  timeScale: "Zeitskala",
  timeScaleLeast: "{count} Minuten - wenigste Detailfläche",
  timeScaleMinutes: "{count} Minuten",
  timeScaleMost: "{count} Minuten - meiste Detailfläche",
  timeScaleShort: "{count} Min.",
  timeZoneChip: "Angezeigte Zeitzone",
  timelineLabel: "Ressourcen-Zeitachse",
  today: "Heute",
  undo: "Rückgängig",
  unitDays: "Tage",
  unitHours: "Stunden",
  unitWeeks: "Wochen",
  unscheduledAll: "Alle",
  unscheduledEmpty: "Alles abgedeckt.",
  unscheduledEmptyInView: "Nichts in diesem Zeitraum.",
  unscheduledFilterLabel: "Ungeplante Elemente filtern",
  unscheduledInView: "Im Zeitraum",
  unscheduledTitle: "Ungeplant",
  weekdaysShort: "So|Mo|Di|Mi|Do|Fr|Sa",
  nextMonth: "Nächster Monat",
  previousMonth: "Vorheriger Monat",
  schedulerSettings: "Planer-Einstellungen",
  fullScreen: "Vollbild",
  fullScreenExit: "Vollbild beenden",
  weekdaysLong: "Sonntag|Montag|Dienstag|Mittwoch|Donnerstag|Freitag|Samstag",
  noDate: "Kein Datum",
  scoreNotCounted: "Diesmal nicht gezählt",
  mustBreakdownTitle: "Muss-Regeln",
  mustRowRest: "Ruhezeit zwischen Schichten",
  mustRowDaysInARow: "Tage in Folge",
  mustRowSkills: "Fähigkeiten",
  mustRowOnLeave: "Abwesend oder nicht verfügbar",
  mustRowOther: "Weitere Muss-Regeln",
  mustKindOverlap: "Doppelbuchung",
  mustKindMaximumHours: "Max. Stunden",
  mustKindSplitParts: "Teildienst",
  mustKindUnlisted: "Sonstige",
  mustRowSummary: "{rule}: {now} aktuell, {proposed} im Vorschlag",
  mustRowOpen: "{rule}: {now} aktuell, {proposed} im Vorschlag. Schichten anzeigen",
  mustUncheckedOne: "Für 1 Person nicht geprüft",
  mustUnchecked: "Für {count} Personen nicht geprüft",
  mustNoAgreementOne: "1 Person hat keine Vereinbarung: Ruhezeit und Tageslimits nicht geprüft.",
  mustNoAgreement: "{count} Personen haben keine Vereinbarung: Ruhezeit und Tageslimits nicht geprüft.",
  mustNoAgreementNobody: "Niemand hat eine Vereinbarung: Ruhezeit und Tageslimits nicht geprüft.",
  proposalMustKeptUncheckedOne: "Muss-Regeln eingehalten · für 1 Person nicht geprüft",
  proposalMustKeptUnchecked: "Muss-Regeln eingehalten · für {count} Personen nicht geprüft",
  drillGroup: "{rule} ({count})",
  drillMore: "und {count} weitere",
  reasonFixesRest: "Behebt die Ruhezeit von {name} ({hours} Std.)",
  reasonFixesDaysInARow: "Behebt die Tage in Folge von {name}",
  reasonFixesSkill: "Behebt eine fehlende Fähigkeit",
  reasonFixesMust: "Behebt einen Muss-Regel-Verstoß",
  reasonAddsRest: "Verkürzt die Ruhezeit von {name} auf {hours} Std.",
  reasonAddsMust: "Verletzt eine Muss-Regel",
  reasonUnpreferred: "{name} arbeitet dann ungern",
  reasonAvoidsUnpreferred: "Vermeidet ungünstige Zeit für {name}",
  reasonFillsOpen: "Besetzt eine offene Schicht",
  reasonPersonFixesOne: "Behebt 1 Regelverstoß",
  reasonPersonFixes: "Behebt {count} Regelverstöße",
  countsOnlyNote: "Großer Dienstplan: nur Anzahlen. Gründe werden nicht gezeigt.",
  tryAgain: "Erneut versuchen",
  menuWhyNot: "Warum nicht…?",
  whyNotPerson: "Person",
  whyNotPlaceholder: "Namen eingeben",
  whyNotNoMatch: "Kein Treffer",
  whyNotNow: "jetzt {name}",
  whyNotChecking: "{name} wird geprüft…",
  whyNotVerdictMustOne: "{name} würde 1 Muss-Regel verletzen",
  whyNotVerdictMust: "{name} würde {count} Muss-Regeln verletzen",
  whyNotVerdictShould: "{name} hält alle Muss-Regeln ein, passt aber schlechter",
  whyNotVerdictEqual: "{name} passt genauso gut.",
  whyNotVerdictEqualReview: "{name} passt genauso gut. Die Optimierung musste wählen.",
  whyNotVerdictBetter: "{name} passt besser.",
  whyNotTakingOff: "{name} verliert die Schicht",
  whyNotPrefers: "{name} arbeitet dann gern",
  ruleSpreadOfShifts: "Verteilung der Schichten",
  ruleMinimumHours: "Mindeststunden",
  whyNotLessEven: "{rule}: ungleichmäßiger",
  whyNotMoreEven: "{rule}: gleichmäßiger",
  whyNotWorse: "{rule}: schlechter",
  whyNotBetter: "{rule}: besser",
  whyNotNoAgreement: "{name} hat keine Vereinbarung: Ruhezeit und Tageslimits nicht geprüft.",
  whyNotUnavailable: "Gerade nicht prüfbar",
  whyNotRetryIn: "Gerade nicht prüfbar. In {seconds} s erneut versuchen.",
  whyNotRosterChanged: "Der Dienstplan hat sich geändert.",
  whyNotAskAgain: "Erneut fragen",
  whyNotAssign: "{name} zuweisen",
  whyNotSwap: "{name} und {other} tauschen",
  whyNotTakes: "{name} übernimmt {shift}",
  whyNotLeftOpen: "{shift} von {name} bliebe offen",
  whyNotInReview: "Für {name} diese Änderung auslassen und nach dem Übernehmen handeln.",
  scorePreferences: "Erfüllte Präferenzen",
  scorePreferencesValue: "{met} von {total}",
  scorePreferencesNone: "Keine Präferenzen erfasst",
  preferencesUnmetTitle: "Nicht erfüllte Präferenzen",
};
