/**
 * The COMPLETE German bundle for the harness locale switch, typed
 * as full SchedulerStrings on purpose: adding a string key without
 * a German translation breaks this build, so the bundle cannot rot
 * into a partial again (Matt 2026-08-24). The PCF adapter feeds
 * resx resources through the same prop in production.
 */
import type { SchedulerStrings } from "../src/stringResources";

export const germanStrings: SchedulerStrings = {
  agendaEmpty: "In diesem Zeitraum ist nichts geplant.",
  apply: "Übernehmen",
  assignedTo: "Zugewiesen an",
  unassigned: "Nicht zugewiesen",
  bandBusyElsewhere: "Anderweitig im Dienst",
  bandPreferred: "Bevorzugt",
  bandUnavailable: "Nicht verfügbar",
  bandUnpreferred: "Ungünstig",
  cancel: "Abbrechen",
  changesSinceMany: "{count} Änderungen seither",
  changesSinceNone: "Keine Änderungen seither",
  changesSinceOne: "{count} Änderung seither",
  close: "Schließen",
  coverage: "Abdeckung",
  currentRosterLabel: "Aktueller Dienstplan",
  delete: "Löschen",
  deleteConfirmAction: "Löschen",
  deleteConfirmCount:
    "{count} Elemente löschen? Dies kann nicht rückgängig gemacht werden.",
  deleteConfirmMessage:
    "{title} löschen? Dies kann nicht rückgängig gemacht werden.",
  deleteConfirmTitle: "Löschen bestätigen",
  dialogBestOptions: "Beste Optionen",
  dialogFinishAfterStart: "Ende muss nach dem Beginn liegen.",
  dialogNameRequired: "Name ist erforderlich.",
  dialogNotAllowed: "Diese Änderung ist nicht zulässig.",
  dialogOtherOptions: "Andere",
  directionEarlier: "Früher",
  directionLater: "Später",
  draftItem: "Neues Element",
  duration: "Dauer",
  emptyResources:
    "Keine Ressourcen vorhanden. Konfiguration der Ansicht prüfen.",
  entitlementGrace: "Zahlung überfällig, Kulanzfrist bis {date}",
  entitlementLapsed: "Chrona-Abonnement abgelaufen. Optimieren und Generieren sind pausiert, bis die Abrechnung geklärt ist.",
  entitlementPaused: "Optimierer pausiert seit {since}. Chrona ist nicht erreichbar; die Planung arbeitet wie gewohnt.",
  entitlementPlanUsage: "Plan und Nutzung",
  entitlementResources: "{scheduled} von {included} Ressourcen in diesem Zeitraum geplant",
  entitlementResourcesAbovePlan: "{scheduled} von {included} Ressourcen geplant, über dem Plan",
  entitlementResourcesNoCeiling: "{scheduled} Ressourcen in diesem Zeitraum geplant",
  entitlementRetry: "Erneut versuchen",
  finish: "Ende",
  flagCauseAssigned: "zugewiesen",
  flagCauseEdited: "bearbeitet",
  flagCausePinned: "angeheftet",
  flagReason:
    "Vom Bedarf nicht mehr benötigt: {required} benötigt, {existing} vorhanden. Behalten, weil es {cause} ist.",
  goToDate: "Zu Datum springen",
  horizonFull:
    "In diesem Planungshorizont können keine weiteren Dienstpläne angelegt werden.",
  horizonHeader: "Planungshorizont {range} ({days} Tage)",
  interval: "Intervall",
  intervalDay: "Tag",
  intervalDaySpan: "Zeitspanne",
  intervalMonth: "Monat",
  intervalWeek: "Woche",
  itemsCount: "{count} Elemente",
  legendBusyElsewhere: "Anderweitig im Dienst",
  legendCustom: "Hervorgehoben",
  legendHoliday: "Feiertag",
  legendNeedsCover: "Besetzung offen",
  legendNonWorking: "Arbeitsfreie Zeit",
  legendPreferred: "Bevorzugte Zeiten",
  legendUnavailable: "Nicht verfügbar",
  legendUnpreferred: "Ungünstige Zeiten",
  menuDeleteCount: "{count} Elemente löschen",
  menuDuplicate: "Duplizieren",
  menuMoveTo: "Verschieben nach...",
  menuMoveToCount: "{count} Elemente verschieben nach...",
  menuOpen: "Öffnen",
  menuOpenRecord: "Datensatz öffnen",
  menuPin: "Anheften",
  menuPinCount: "{count} Elemente anheften",
  menuReassign: "Neu zuweisen an...",
  menuReassignCount: "{count} Elemente neu zuweisen an...",
  menuUnpin: "Lösen",
  menuUnpinCount: "{count} Elemente lösen",
  groupByLabel: "Zeilen gruppieren",
  groupByNone: "Keine Gruppierung",
  ungrouped: "Ohne Gruppe",
  hideUnscheduledPanel: "Ungeplant-Bereich ausblenden",
  unscheduledToggle: "Ungeplant ({count})",
  conversionOptimize: "Optimieren",
  conversionTitle: "Der ganze Plan, in einem Zug gel\u00f6st",
  conversionPitchProblem:
    "Wer Eintrag f\u00fcr Eintrag plant, \u00fcbersieht die Wechselwirkungen.",
  conversionPitchMechanism:
    "Chrona betrachtet den ganzen Plan auf einmal \u2014 F\u00e4higkeiten, Verf\u00fcgbarkeit, Stunden, Kosten und Konflikte.",
  conversionInfoLead: "Optional. Kostenlos testen.",
  conversionInfoBody:
    "Die Verbindung mit Chrona \u00e4ndert nichts daran, wie dieser Planer funktioniert.",
  conversionClaimBase: "Offene Arbeit besetzt. Konflikte gel\u00f6st.",
  conversionClaimRespected: "{list} ber\u00fccksichtigt.",
  capabilityAssignment: "Zuweisung",
  capabilityLocks: "Sperren",
  capabilityRoles: "Rollen",
  capabilityAvailability: "Verf\u00fcgbarkeit",
  capabilityHours: "Stunden",
  capabilityCost: "Kosten",
  listAnd: "und",
  solveCapabilitiesLine: "Optimiert mit: {list}",
  generate: "Generieren",
  generateWindowTitle: "Aus Vorlagen generieren",
  generateWindowIntro:
    "Erweitert die Vorlagen zu offenen Einträgen für diesen Zeitraum. Ein erneuter Lauf gleicht ab: unberührter Überschuss wird entfernt, bearbeitete oder zugewiesene Einträge bleiben und werden markiert.",
  generateWindowFrom: "Von",
  generateWindowTo: "Bis",
  generateWindowAction: "Generieren",
  conversionCountsSuffix: " \u2014 lokal gez\u00e4hlt, nichts gesendet.",
  conversionCoverageGaps: "{gaps} Abdeckungsl\u00fccken",
  conversionSampleTitle: "Ein Beispiellauf",
  conversionSampleBefore: "Vorher",
  conversionSampleAfter: "Nachher: das optimierte Ergebnis",
  conversionSampleCounts: "{open} offene Eintr\u00e4ge \u00b7 {conflicts} Konflikte",
  conversionAxisLabels: "Mo 8:00|Mo 12:00|Mo 16:00|Di 8:00",
  conversionSentTitle: "Was ein echter Lauf verwenden w\u00fcrde",
  conversionSentWork:
    "Arbeitseintr\u00e4ge \u2014 Zeiten, Anforderungen, aktuelle Zuweisung als ID",
  conversionSentPeople:
    "Personen \u2014 Ressourcen-IDs, F\u00e4higkeiten, Verf\u00fcgbarkeitsfenster, Stunden und Kostens\u00e4tze",
  conversionSentNothingElse:
    "Sonst nichts \u2014 keine Namen, keine Notizen, keine Kontaktdaten, keine fremden Datens\u00e4tze",
  conversionInspect: "Den exakten Payload pr\u00fcfen",
  conversionPayloadNote: "Genau dieses JSON. Nichts wird gesendet, bis Sie verbinden.",
  conversionLockLine:
    "Kostenlos. Keine Kreditkarte. Nichts wird gesendet, bis Sie verbinden. Ein Beispiellauf \u00e4ndert nie Ihren Zeitplan.",
  conversionAllClear:
    "In den aktuellen Daten ist nichts markiert \u2014 lokal gez\u00e4hlt, nichts gesendet.",
  conversionNotNow: "Nicht jetzt",
  conversionConnect: "Kostenlosen Beispiellauf starten",
  conversionLearnMore: "Mehr erfahren",
  menuAssign: "Personal zuweisen\u2026",
  unscheduleConfirmTitle: "Zuweisung aufheben",
  unscheduleConfirmMessage:
    "Zuweisung von {title} aufheben? Die Schicht beh\u00e4lt ihre Zeit und kehrt zur Neuzuweisung in \u201eUngeplant\u201c zur\u00fcck.",
  unscheduleConfirmAction: "Aufheben",
  unscheduledLaneLabel: "Ungeplant \u00b7 {count}",
  assignTitle: "Personal zuweisen",
  assignBestOptions: "Beste Optionen",
  assignNotAvailable: "Nicht verf\u00fcgbar",
  assignShowEveryone: "Alle anzeigen ({count})",
  assignSearchPlaceholder: "Personal suchen",
  assignHoursLeft: "{left} von {capacity} Std. frei",
  assignReasonMissingSkill: "Fehlende F\u00e4higkeit: {tag}",
  assignReasonUnavailable: "Nicht verf\u00fcgbar {range}",
  assignReasonBusy: "Bereits im Dienst {range}",
  assignReasonHours: "W\u00fcrde {capacity} Std. \u00fcberschreiten",
  assignEmpty: "Kein passendes Personal.",
  assignAction: "{name} zuweisen",
  menuUnschedule: "Zuweisung aufheben",
  modeOperate: "Betrieb",
  modePlan: "Planung",
  monthMore: "+{count} weitere",
  monthsLong: "Januar|Februar|März|April|Mai|Juni|Juli|August|September|Oktober|November|Dezember",
  monthsShort: "Jan|Feb|Mär|Apr|Mai|Jun|Jul|Aug|Sep|Okt|Nov|Dez",
  moveAmount: "Anzahl",
  moveDialogTitle: "Verschieben nach",
  moveDirection: "Richtung",
  moveUnit: "Einheit",
  name: "Name",
  needsCover: "Besetzung offen",
  newEvent: "Neuer Termin",
  next: "Weiter",
  noticeBlocked: "Blockiert: {reason}",
  noticeWarning: "Hinweis: {reason}",
  optimizePeriod: "Diesen Zeitraum optimieren",
  optionMissingSkills: "fehlend: {skills}",
  optionSkillMismatch: "{count}/{total} Kenntnisse fehlen",
  periodNext: "Nächster Zeitraum",
  periodOf: "Tag {day} von {days}",
  periodPrevious: "Vorheriger Zeitraum",
  pinnedNotice: "Angeheftet - zum Ändern lösen.",
  planningPeriodLabel: "Planungszeitraum",
  previous: "Zurück",
  proposalAppliedMany: "{count} Vorschläge übernommen",
  proposalAppliedOne: "1 Vorschlag übernommen",
  proposalApply: "Übernehmen",
  proposalBlocked: "{count} blockiert",
  proposalChanges: "{count} vorgeschlagene Änderungen",
  proposalDiscard: "Verwerfen",
  proposalEmpty: "Keine Änderungen vorgeschlagen",
  proposalNotes: "{count} Hinweise",
  proposalChangeOne: "1 vorgeschlagene Änderung",
  proposalDropped: "{count} ausgelassen",
  proposalDropChange: "Änderung auslassen",
  proposalKeepChange: "Änderung behalten",
  proposalReviewHint: "Vorschlag in Prüfung. Übernehmen oder verwerfen, um zu bearbeiten.",
  proposalShowCurrent: "Aktuell",
  proposalShowProposed: "Vorschlag",
  proposalPanelTitle: "Vorgeschlagene Änderungen",
  proposalGroupAssigned: "Zugewiesen ({count})",
  proposalGroupMoved: "Verschoben ({count})",
  proposalGroupBlocked: "Blockiert ({count})",
  proposalGroupUnassigned: "Nicht zugewiesen ({count})",
  proposalMustBroken: "Einige Muss-Regeln verletzt",
  proposalMustKept: "Alle Muss-Regeln eingehalten",
  proposalOpenMany: "{count} offene Schichten",
  proposalOpenOne: "1 offene Schicht",
  proposalWas: "vorher {detail}",
  solveQueued: "In der Warteschlange...",
  solveElapsed: "{seconds} s",
  publishAction: "Veröffentlichen",
  publishBlockedSequential:
    "Zuerst den vorherigen Dienstplan veröffentlichen.",
  publishConfirmMessage:
    "{range} veröffentlichen? Der Dienstplan wird für Mitarbeitende sichtbar, spätere Änderungen werden gegen diese Veröffentlichung protokolliert.",
  publishConfirmTitle: "Dienstplan veröffentlichen",
  publishByLine: "Veröffentlichen bis {date}",
  publishOverdueDay: "{days} Tag überfällig",
  publishOverdueDays: "{days} Tage überfällig",
  publishedLine: "Veröffentlicht am {date}",
  railAddRoster: "Dienstplan hinzufügen",
  railLabel: "Planungshorizont",
  railScrollBack: "Zurück blättern",
  railScrollForward: "Vorwärts blättern",
  redo: "Wiederholen",
  rosterActions: "Dienstplan-Aktionen",
  rosterCardLabel: "Dienstplan {range}",
  rosterDeleteConfirmMessage:
    "{range} löschen? Offene generierte Schichten werden entfernt; zugewiesene Schichten bleiben im Plan.",
  rosterDeleteConfirmTitle: "Dienstplan löschen",
  rosterDeleted: "Dienstplan {range} gelöscht: {count} offene Schichten entfernt",
  rosterGenerate: "Schichten generieren",
  rosterProgressFull: "Vollständig geplant",
  rosterProgressNotStarted: "Nicht begonnen",
  rosterPercentScheduled: "{percent}% geplant",
  reassignDialogTitle: "Neu zuweisen an",
  requiredSkills: "Kenntnisse",
  resizeResources: "Ressourcenspalte anpassen",
  resizeUnscheduled: "Ungeplant-Bereich anpassen",
  resourceHeader: "Ressource",
  save: "Speichern",
  savedViews: "Ansichten",
  scopeNotice: "Außerhalb dieses Dienstplans ändert sich nichts.",
  solve: "Optimieren",
  solveFailed: "Optimierung fehlgeschlagen: {message}",
  solveQuotaRemaining: "{remaining} von {limit} kostenlosen Optimierungen heute übrig",
  solveQuotaExhausted:
    "Die kostenlosen Optimierungen für heute sind aufgebraucht. Morgen gibt es mehr — oder upgraden Sie für unbegrenzte Läufe.",
  solveQuotaUpgrade: "Upgrade",
  resumeFinished: "Eine Optimierung wurde abgeschlossen, während Sie weg waren.",
  resumeRunning: "Für diesen Plan läuft gerade eine Optimierung.",
  resumeChanged:
    "Eine Optimierung wurde abgeschlossen, während Sie weg waren, aber der Plan hat sich seitdem geändert. Das Ergebnis passt nicht mehr.",
  resumeReview: "Ansehen",
  resumeFollow: "Verfolgen",
  resumeDiscard: "Verwerfen",
  openChronaAccount: "Chrona-Konto öffnen",
  solveSolving: "Wird optimiert...",
  start: "Beginn",
  statusDraft: "Entwurf",
  statusLocked: "Gesperrt",
  statusPublished: "Veröffentlicht",
  timeScale: "Zeitskala",
  timeScaleLeast: "{count} Minuten - wenigste Detailfläche",
  timeScaleMinutes: "{count} Minuten",
  timeScaleMost: "{count} Minuten - meiste Detailfläche",
  timeScaleShort: "{count} Min.",
  timeZoneChip: "Angezeigte Zeitzone",
  timelineLabel: "Ressourcen-Zeitachse",
  today: "Heute",
  undo: "Rückgängig",
  unpublishAction: "Veröffentlichung aufheben",
  unpublishBlockedSequential:
    "Zuerst den nachfolgenden Dienstplan zurückziehen.",
  unpublishConfirmMessage:
    "Veröffentlichung von {range} aufheben? Der Dienstplan wird wieder zum Entwurf; die Veröffentlichungshistorie bleibt für die Prüfung erhalten.",
  unpublishConfirmTitle: "Veröffentlichung aufheben",
  unitDays: "Tage",
  unitHours: "Stunden",
  unitWeeks: "Wochen",
  unscheduledAll: "Alle",
  unscheduledEmpty: "Alles abgedeckt.",
  unscheduledEmptyInView: "Nichts in diesem Zeitraum.",
  unscheduledFilterLabel: "Ungeplante Elemente filtern",
  unscheduledInView: "Im Zeitraum",
  unscheduledTitle: "Nicht eingeplant",
  weekdaysShort: "So|Mo|Di|Mi|Do|Fr|Sa",
  nextMonth: "Nächster Monat",
  previousMonth: "Vorheriger Monat",
  schedulerSettings: "Planer-Einstellungen",
  weekdaysLong: "Sonntag|Montag|Dienstag|Mittwoch|Donnerstag|Freitag|Samstag",
  noDate: "Kein Datum",
};
