import type { SchedulerStrings } from "../src/stringResources";

/** Compact italian labels; keep placeholders and date-name order intact. */
export const italianStrings: SchedulerStrings = {
  "agendaEmpty": "Nulla pianificato in questo periodo.",
  "apply": "Applica",
  "assignedTo": "Assegnato a",
  "unassigned": "Non assegnato",
  "cancel": "Annulla",
  "close": "Chiudi",
  "delete": "Elimina",
  "deleteConfirmAction": "Elimina",
  "deleteConfirmCount": "Eliminare {count} elementi? L'azione è irreversibile.",
  "deleteConfirmMessage": "Eliminare {title}? L'azione è irreversibile.",
  "deleteConfirmTitle": "Conferma eliminazione",
  "dialogFinishAfterStart": "La fine deve seguire l'inizio.",
  "directionEarlier": "Prima",
  "directionLater": "Dopo",
  "dialogNameRequired": "Il nome è obbligatorio.",
  "dialogBestOptions": "Opzioni migliori",
  "dialogNotAllowed": "Questa modifica non è consentita.",
  "dialogOtherOptions": "Altre",
  "draftItem": "Nuovo elemento",
  "duration": "Durata",
  "emptyResources": "Nessuna risorsa. Controlla le impostazioni della vista.",
  "entitlementGrace": "Pagamento scaduto. Proroga fino al {date}",
  "entitlementLapsed": "Abbonamento Chrona scaduto. Ottimizzazione e generazione sospese fino alla regolarizzazione del pagamento.",
  "entitlementPaused": "Ottimizzazione sospesa dal {since}. Chrona non è raggiungibile; puoi continuare a pianificare.",
  "entitlementPlanUsage": "Piano e utilizzo",
  "entitlementResources": "{scheduled} risorse su {included} pianificate nel periodo",
  "entitlementResourcesAbovePlan": "{scheduled} risorse su {included} pianificate, oltre il piano",
  "entitlementResourcesNoCeiling": "{scheduled} risorse pianificate nel periodo",
  "entitlementRetry": "Riprova",
  "finish": "Fine",
  "flagCauseAssigned": "assegnato",
  "flagCauseEdited": "modificato",
  "flagCausePinned": "fissato",
  "flagReason": "Non più necessario: {required} richiesti, {existing} presenti. Mantenuto perché {cause}.",
  "goToDate": "Vai alla data",
  "interval": "Intervallo",
  "intervalDay": "Giorno",
  "itemsCount": "{count} elementi",
  "intervalDaySpan": "Fascia",
  "intervalMonth": "Mese",
  "intervalWeek": "Settimana",
  "legendBusyElsewhere": "Occupato altrove",
  "legendCustom": "Evidenziato",
  "legendHoliday": "Festivo",
  "legendNeedsCover": "Da coprire",
  "legendNonWorking": "Fuori orario",
  "legendPreferred": "Orari preferiti",
  "legendUnavailable": "Non disponibile",
  "legendUnpreferred": "Orari non preferiti",
  "menuDeleteCount": "Elimina {count} elementi",
  "menuDuplicate": "Duplica",
  "menuOpen": "Apri",
  "menuOpenRecord": "Apri record",
  "menuPin": "Fissa",
  "menuPinCount": "Fissa {count} elementi",
  "menuUnpin": "Sblocca",
  "menuUnpinCount": "Sblocca {count} elementi",
  "menuMoveTo": "Sposta a…",
  "menuMoveToCount": "Sposta {count} elementi a…",
  "menuReassign": "Riassegna a…",
  "menuReassignCount": "Riassegna {count} elementi a…",
  "groupByLabel": "Raggruppa righe",
  "groupByNone": "Nessun gruppo",
  "ungrouped": "Senza gruppo",
  "hideUnscheduledPanel": "Nascondi elementi non pianificati",
  "unscheduledToggle": "Non pianificati ({count})",
  "conversionOptimize": "Ottimizza",
  "conversionTitle": "Tutti i turni, in una volta",
  "conversionPitchProblem": "Pianificare un elemento alla volta nasconde le interazioni.",
  "conversionPitchMechanism": "Chrona valuta tutti i turni: competenze, disponibilità, ore, costi e conflitti.",
  "conversionInfoLead": "Facoltativo. Prova gratis.",
  "conversionInfoBody": "Collegare Chrona non cambia il funzionamento del calendario.",
  "conversionClaimBase": "Lavoro assegnato. Conflitti risolti.",
  "conversionClaimRespected": "Criteri rispettati: {list}.",
  "capabilityAssignment": "assegnazioni",
  "capabilityLocks": "blocchi",
  "capabilityRoles": "ruoli",
  "capabilityAvailability": "disponibilità",
  "capabilityHours": "ore",
  "capabilityCost": "costi",
  "listAnd": "e",
  "solveCapabilitiesLine": "Ottimizzazione con: {list}",
  "conversionCountsSuffix": " — conteggio locale, nessun invio.",
  "conversionCoverageGaps": "{gaps} carenze di copertura",
  "conversionSampleTitle": "Esempio di ottimizzazione",
  "conversionSampleBefore": "Prima",
  "conversionSampleAfter": "Dopo l'ottimizzazione",
  "conversionSampleCounts": "{open} elementi da assegnare · {conflicts} conflitti",
  "conversionAxisLabels": "Lun 8:00|Lun 12:00|Lun 16:00|Mar 8:00",
  "conversionSentTitle": "Dati per un'ottimizzazione reale",
  "conversionSentWork": "Attività: orari, requisiti e ID dell'assegnatario",
  "conversionSentPeople": "Persone: ID risorsa, competenze, disponibilità, ore e tariffe",
  "conversionSentNothingElse": "Nient'altro: niente nomi, note, contatti o record non pertinenti",
  "conversionInspect": "Vedi i dati esatti",
  "conversionPayloadNote": "Questo JSON esatto. Nessun invio prima del collegamento.",
  "conversionLockLine": "Gratis. Senza carta. Nessun invio prima del collegamento. L'esempio non modifica mai i tuoi turni.",
  "conversionAllClear": "Nessuna segnalazione nei dati attuali. Conteggio locale, nessun invio.",
  "conversionNotNow": "Non ora",
  "conversionConnect": "Prova gratis",
  "conversionLearnMore": "Scopri di più",
  "menuAssign": "Assegna personale…",
  "menuUnschedule": "Rimuovi assegnazione",
  "unscheduleConfirmTitle": "Rimuovi assegnazione",
  "unscheduleConfirmMessage": "Rimuovere l'assegnazione di {title}? Il turno mantiene l'orario e torna in Non pianificati per riassegnarlo.",
  "unscheduleConfirmAction": "Rimuovi assegnazione",
  "unscheduledLaneLabel": "Non pianificati · {count}",
  "assignTitle": "Assegna personale",
  "assignBestOptions": "Opzioni migliori",
  "assignNotAvailable": "Non disponibile",
  "assignShowEveryone": "Mostra tutti ({count})",
  "assignSearchPlaceholder": "Cerca personale",
  "assignHoursLeft": "{left} h residue su {capacity} h",
  "assignReasonUnavailable": "Non disponibile {range}",
  "assignReasonBusy": "Già al lavoro {range}",
  "assignReasonHours": "Supererebbe {capacity} h",
  "assignEmpty": "Nessuna persona trovata.",
  "assignAction": "Assegna a {name}",
  "monthMore": "+{count} altri",
  "monthsLong": "gennaio|febbraio|marzo|aprile|maggio|giugno|luglio|agosto|settembre|ottobre|novembre|dicembre",
  "monthsShort": "gen|feb|mar|apr|mag|giu|lug|ago|set|ott|nov|dic",
  "moveAmount": "Quantità",
  "moveDialogTitle": "Sposta a",
  "moveDirection": "Direzione",
  "moveUnit": "Unità",
  "name": "Nome",
  "needsCover": "Da coprire",
  "newEvent": "Nuovo evento",
  "next": "Avanti",
  "noticeBlocked": "Bloccato: {reason}",
  "noticeWarning": "Nota: {reason}",
  "pinnedNotice": "Fissato. Sblocca per modificare.",
  "previous": "Indietro",
  "reassignDialogTitle": "Riassegna a",
  "periodNext": "Periodo successivo",
  "periodOf": "giorno {day} di {days}",
  "redo": "Ripeti",
  "rosterOpenShifts": "Turni non assegnati",
  "periodPrevious": "Periodo precedente",
  "proposalApply": "Applica",
  "proposalAppliedMany": "{count} suggerimenti applicati",
  "proposalAppliedOne": "1 suggerimento applicato",
  "proposalDiscard": "Scarta",
  "proposalEmpty": "Nessuna modifica proposta",
  "proposalDropped": "{count} scartati",
  "proposalDropChange": "Scarta modifica",
  "proposalKeepChange": "Mantieni modifica",
  "proposalKeepAll": "Mantieni tutte",
  "proposalKeepNone": "Non mantenere nessuna",
  "proposalPerPerson": "{count} modifiche, riassunte per persona.",
  "proposalPersonShifts": "{count} turni · {hours} h",
  "proposalPersonShiftOne": "1 turno · {hours} h",
  "proposalHeldBack": "Trattenute ({count})",
  "proposalHeldBackHint": "Ognuna creerebbe una doppia assegnazione, quindi Applica la esclude.",
  "proposalApplyAll": "Applica tutte e {count}",
  "proposalApplySome": "Applica {kept} su {count}",
  "proposalReviewHint": "Proposta in esame. Applica o scarta per modificare.",
  "proposalShowCurrent": "Attuale",
  "proposalShowProposed": "Proposto",
  "proposalHoldCompare": "Tieni premuto per confrontare",
  "proposalChangesOnly": "Solo modifiche",
  "proposalPanelTitle": "Modifiche proposte",
  "proposalPanelToggle": "Modifiche proposte ({count})",
  "proposalGroupAssigned": "Assegnati ({count})",
  "proposalGroupMoved": "Spostati ({count})",
  "proposalGroupUnassigned": "Non assegnati ({count})",
  "proposalMustBroken": "Alcune regole obbligatorie violate",
  "proposalMustKept": "Tutte le regole obbligatorie rispettate",
  "proposalWas": "prima: {detail}",
  "proposalTitle": "Turni proposti",
  "proposalSummaryChangeOne": "1 modifica",
  "proposalSummaryChanges": "{count} modifiche",
  "proposalFilled": "{filled} turni coperti su {total}",
  "scorecardLabel": "Rispetto ai turni attuali",
  "scoreFilled": "Turni coperti",
  "scoreMustBroken": "Regole obbligatorie violate",
  "scoreNone": "Nessuna",
  "scoreSome": "Alcune",
  "scoreNotChecked": "Non verificato",
  "scoreChanges": "Modifiche",
  "scorePeople": "Persone coinvolte",
  "scoreVsNow": "{delta} vs attuale",
  "scoreNoChange": "Invariato",
  "scoreOfPeople": "su {count} persone",
  "scorecardToggle": "Indicatori",
  "scoreSearch": "Turnazioni valutate",
  "scoreSearchNote": "{better} miglioramenti · {seconds} s",
  "scoreSearchNoteOne": "1 miglioramento · {seconds} s",
  "scoreSearchUnit": "versioni",
  "proposalCheckFoundMany": "{count} modifiche non sono più aggiornate. Controllale, poi applica di nuovo.",
  "proposalCheckFoundOne": "1 modifica non è più aggiornata. Controllala, poi applica di nuovo.",
  "proposalDoubleBookingMany": "{count} doppie assegnazioni",
  "proposalDoubleBookingOne": "1 doppia assegnazione",
  "proposalDoubleBooks": "Doppia assegnazione di {person} con {title}",
  "proposalGroupOutOfDate": "Non aggiornate ({count})",
  "proposalOutOfDate": "{count} non aggiornate",
  "proposalReasonChanged": "Modificato dopo la creazione del piano",
  "proposalReasonNewShift": "{person} ha ora un altro turno a quest'ora",
  "proposalReasonPersonChanged": "I dati di {person} sono cambiati dopo la creazione del piano",
  "proposalReasonStarted": "Già iniziato",
  "proposalReasonUnavailable": "{person} ora non è disponibile a quest'ora",
  "solvePeriodPassed": "Questo periodo è passato",
  "solveQueued": "In coda…",
  "solveElapsed": "{seconds} s",
  "requiredSkills": "Competenze richieste",
  "resizeResources": "Ridimensiona colonna risorse",
  "resizeUnscheduled": "Ridimensiona pannello non pianificati",
  "resourceHeader": "Risorsa",
  "save": "Salva",
  "savedViews": "Viste",
  "start": "Inizio",
  "solve": "Ottimizza",
  "solveFailed": "Ottimizzazione fallita: {message}",
  "solveQuotaRemaining": "Restano {remaining} ottimizzazioni gratuite su {limit} oggi",
  "solveQuotaExhausted": "Ottimizzazioni gratuite di oggi esaurite. Torna domani o passa al piano illimitato.",
  "solveQuotaUpgrade": "Cambia piano",
  "resumeFinished": "Un'ottimizzazione è terminata mentre eri via.",
  "resumeRunning": "Un'ottimizzazione è in corso per questi turni.",
  "resumeChanged": "Un'ottimizzazione è terminata mentre eri via, ma i turni sono cambiati. Il risultato non è più applicabile.",
  "resumeReview": "Rivedi",
  "resumeFollow": "Segui",
  "resumeDiscard": "Scarta",
  "openChronaAccount": "Apri account Chrona",
  "solveSolving": "Ottimizzazione…",
  "timeScale": "Scala temporale",
  "timeScaleLeast": "{count} minuti – meno spazio per i dettagli",
  "timeScaleMinutes": "{count} minuti",
  "timeScaleMost": "{count} minuti – più spazio per i dettagli",
  "timeScaleShort": "{count} min",
  "timeZoneChip": "Fuso orario visualizzato",
  "timelineLabel": "Cronologia risorse",
  "today": "Oggi",
  "undo": "Annulla",
  "unitDays": "Giorni",
  "unitHours": "Ore",
  "unitWeeks": "Settimane",
  "unscheduledAll": "Tutti",
  "unscheduledEmpty": "Tutto coperto.",
  "unscheduledEmptyInView": "Nulla in questo periodo.",
  "unscheduledFilterLabel": "Filtra elementi non pianificati",
  "unscheduledInView": "Nella vista",
  "unscheduledTitle": "Non pianificati",
  "weekdaysShort": "dom|lun|mar|mer|gio|ven|sab",
  "nextMonth": "Mese successivo",
  "previousMonth": "Mese precedente",
  "schedulerSettings": "Impostazioni del calendario",
  "fullScreen": "Schermo intero",
  "fullScreenExit": "Esci da schermo intero",
  "weekdaysLong": "domenica|lunedì|martedì|mercoledì|giovedì|venerdì|sabato",
  "noDate": "Senza data",
  "scoreNotCounted": "Non conteggiato stavolta",
  "mustBreakdownTitle": "Regole obbligatorie",
  "mustRowRest": "Riposo tra turni",
  "mustRowDaysInARow": "Giorni consecutivi",
  "mustRowSkills": "Competenze",
  "mustRowOnLeave": "Assente o non disponibile",
  "mustRowOther": "Altre regole obbligatorie",
  "mustKindOverlap": "Doppia assegnazione",
  "mustKindMaximumHours": "Ore max",
  "mustKindSplitParts": "Turno spezzato",
  "mustKindUnlisted": "Altre",
  "mustRowSummary": "{rule}: {now} ora, {proposed} nella proposta",
  "mustRowOpen": "{rule}: {now} ora, {proposed} nella proposta. Mostra turni",
  "mustUncheckedOne": "Non verificato per 1 persona",
  "mustUnchecked": "Non verificato per {count} persone",
  "mustNoAgreementOne": "1 persona non ha un accordo: riposo e limiti di giorni non verificati.",
  "mustNoAgreement": "{count} persone non hanno un accordo: riposo e limiti di giorni non verificati.",
  "mustNoAgreementNobody": "Nessuno ha un accordo: riposo e limiti di giorni non verificati.",
  "proposalMustKeptUncheckedOne": "Regole obbligatorie rispettate · non verificato per 1 persona",
  "proposalMustKeptUnchecked": "Regole obbligatorie rispettate · non verificato per {count} persone",
  "drillGroup": "{rule} ({count})",
  "drillMore": "e altri {count}",
  "reasonFixesRest": "Corregge il riposo di {name} ({hours} h)",
  "reasonFixesDaysInARow": "Corregge i giorni consecutivi di {name}",
  "reasonFixesSkill": "Corregge una competenza mancante",
  "reasonFixesMust": "Corregge una regola obbligatoria violata",
  "reasonAddsRest": "Crea un riposo breve per {name} ({hours} h)",
  "reasonAddsMust": "Viola una regola obbligatoria",
  "reasonUnpreferred": "{name} preferisce non lavorare in quell'orario",
  "reasonAvoidsUnpreferred": "Evita gli orari non preferiti di {name}",
  "reasonFillsOpen": "Copre un turno non assegnato",
  "reasonPersonFixesOne": "Corregge 1 violazione",
  "reasonPersonFixes": "Corregge {count} violazioni",
  "countsOnlyNote": "Turni numerosi: solo conteggi. I motivi non sono mostrati.",
  "tryAgain": "Riprova",
  "menuWhyNot": "Perché non…?",
  "whyNotPerson": "Persona",
  "whyNotPlaceholder": "Digita un nome",
  "whyNotNoMatch": "Nessun risultato",
  "whyNotNow": "ora {name}",
  "whyNotChecking": "Verifica di {name}…",
  "whyNotVerdictMustOne": "{name} violerebbe 1 regola obbligatoria",
  "whyNotVerdictMust": "{name} violerebbe {count} regole obbligatorie",
  "whyNotVerdictShould": "{name} rispetta tutte le regole obbligatorie ma si adatta peggio",
  "whyNotVerdictEqual": "{name} si adatta altrettanto bene.",
  "whyNotVerdictEqualReview": "{name} si adatta altrettanto bene. L'ottimizzazione ha dovuto scegliere.",
  "whyNotVerdictBetter": "{name} si adatta meglio.",
  "whyNotTakingOff": "{name} perde il turno",
  "whyNotPrefers": "{name} preferisce lavorare in quell'orario",
  "ruleSpreadOfShifts": "Distribuzione dei turni",
  "ruleMinimumHours": "Ore minime",
  "whyNotLessEven": "{rule}: meno equilibrata",
  "whyNotMoreEven": "{rule}: più equilibrata",
  "whyNotWorse": "{rule}: peggio",
  "whyNotBetter": "{rule}: meglio",
  "whyNotNoAgreement": "{name} non ha un accordo: riposo e limiti di giorni non verificati.",
  "whyNotUnavailable": "Impossibile verificare ora",
  "whyNotRetryIn": "Impossibile verificare ora. Riprova tra {seconds} s.",
  "whyNotRosterChanged": "I turni sono cambiati.",
  "whyNotAskAgain": "Chiedi di nuovo",
  "whyNotAssign": "Assegna {name}",
  "whyNotSwap": "Scambia {name} e {other}",
  "whyNotTakes": "{name} prende {shift}",
  "whyNotLeftOpen": "{shift} di {name} resterebbe scoperto",
  "whyNotInReview": "Per usare {name}, scarta questa modifica e agisci dopo Applica.",
  "scorePreferences": "Preferenze rispettate",
  "scorePreferencesValue": "{met} su {total}",
  "scorePreferencesNone": "Nessuna preferenza inserita",
  "preferencesUnmetTitle": "Preferenze non rispettate"
};
