import type { SchedulerStrings } from "../src/stringResources";

/** Compact italian labels; keep placeholders and date-name order intact. */
export const italianStrings: SchedulerStrings = {
  "agendaEmpty": "Nulla pianificato in questo periodo.",
  "apply": "Applica",
  "assignedTo": "Assegnato a",
  "unassigned": "Non assegnato",
  "bandBusyElsewhere": "Occupato altrove",
  "bandPreferred": "Preferito",
  "bandUnavailable": "Non disponibile",
  "bandUnpreferred": "Non preferito",
  "cancel": "Annulla",
  "close": "Chiudi",
  "delete": "Elimina",
  "deleteConfirmAction": "Elimina",
  "deleteConfirmCount": "Eliminare {count} elementi? L'azione è irreversibile.",
  "deleteConfirmMessage": "Eliminare {title}? L'azione è irreversibile.",
  "deleteConfirmTitle": "Conferma eliminazione",
  "dialogFinishAfterStart": "La fine deve seguire l'inizio.",
  "changesSinceMany": "{count} modifiche dal",
  "changesSinceNone": "Nessuna modifica dal",
  "changesSinceOne": "{count} modifica dal",
  "coverage": "Copertura",
  "currentRosterLabel": "Turni attuali",
  "directionEarlier": "Prima",
  "directionLater": "Dopo",
  "dialogNameRequired": "Il nome è obbligatorio.",
  "dialogBestOptions": "Opzioni migliori",
  "dialogNotAllowed": "Questa modifica non è consentita.",
  "dialogOtherOptions": "Altre",
  "draftItem": "Nuovo elemento",
  "duration": "Durata",
  "emptyResources": "Nessuna risorsa. Controlla le impostazioni della vista.",
  "entitlementGrace": "Pagamento scaduto. Proroga fino al {date}",
  "entitlementLapsed": "Abbonamento Chrona scaduto. Ottimizzazione e generazione sospese fino alla regolarizzazione del pagamento.",
  "entitlementPaused": "Ottimizzazione sospesa dal {since}. Chrona non è raggiungibile; puoi continuare a pianificare.",
  "entitlementPlanUsage": "Piano e utilizzo",
  "entitlementResources": "{scheduled} risorse su {included} pianificate nel periodo",
  "entitlementResourcesAbovePlan": "{scheduled} risorse su {included} pianificate, oltre il piano",
  "entitlementResourcesNoCeiling": "{scheduled} risorse pianificate nel periodo",
  "entitlementRetry": "Riprova",
  "finish": "Fine",
  "flagCauseAssigned": "assegnato",
  "flagCauseEdited": "modificato",
  "flagCausePinned": "fissato",
  "flagReason": "Non più necessario: {required} richiesti, {existing} presenti. Mantenuto perché {cause}.",
  "goToDate": "Vai alla data",
  "horizonFull": "Non puoi aggiungere altri turni in questo orizzonte.",
  "horizonHeader": "Orizzonte {range} ({days} giorni)",
  "interval": "Intervallo",
  "intervalDay": "Giorno",
  "itemsCount": "{count} elementi",
  "intervalDaySpan": "Fascia",
  "intervalMonth": "Mese",
  "intervalWeek": "Settimana",
  "legendBusyElsewhere": "Occupato altrove",
  "legendCustom": "Evidenziato",
  "legendHoliday": "Festivo",
  "legendNeedsCover": "Da coprire",
  "legendNonWorking": "Fuori orario",
  "legendPreferred": "Orari preferiti",
  "legendUnavailable": "Non disponibile",
  "legendUnpreferred": "Orari non preferiti",
  "menuDeleteCount": "Elimina {count} elementi",
  "menuDuplicate": "Duplica",
  "menuOpen": "Apri",
  "menuOpenRecord": "Apri record",
  "menuPin": "Fissa",
  "menuPinCount": "Fissa {count} elementi",
  "menuUnpin": "Sblocca",
  "menuUnpinCount": "Sblocca {count} elementi",
  "menuMoveTo": "Sposta a…",
  "menuMoveToCount": "Sposta {count} elementi a…",
  "menuReassign": "Riassegna a…",
  "menuReassignCount": "Riassegna {count} elementi a…",
  "groupByLabel": "Raggruppa righe",
  "groupByNone": "Nessun gruppo",
  "ungrouped": "Senza gruppo",
  "hideUnscheduledPanel": "Nascondi elementi non pianificati",
  "unscheduledToggle": "Non pianificati ({count})",
  "conversionOptimize": "Ottimizza",
  "conversionTitle": "Tutti i turni, in una volta",
  "conversionPitchProblem": "Pianificare un elemento alla volta nasconde le interazioni.",
  "conversionPitchMechanism": "Chrona valuta tutti i turni: competenze, disponibilità, ore, costi e conflitti.",
  "conversionInfoLead": "Facoltativo. Prova gratis.",
  "conversionInfoBody": "Collegare Chrona non cambia il funzionamento del calendario.",
  "conversionClaimBase": "Lavoro assegnato. Conflitti risolti.",
  "conversionClaimRespected": "Criteri rispettati: {list}.",
  "capabilityAssignment": "assegnazioni",
  "capabilityLocks": "blocchi",
  "capabilityRoles": "ruoli",
  "capabilityAvailability": "disponibilità",
  "capabilityHours": "ore",
  "capabilityCost": "costi",
  "listAnd": "e",
  "solveCapabilitiesLine": "Ottimizzazione con: {list}",
  "generate": "Genera",
  "generateWindowTitle": "Genera da modelli",
  "generateWindowIntro": "Crea elementi da assegnare dai modelli per il periodo. Ripetendo, rimuove l'eccesso intatto e conserva e segnala gli elementi modificati o assegnati.",
  "generateWindowFrom": "Dal",
  "generateWindowTo": "Al",
  "generateWindowAction": "Genera",
  "conversionCountsSuffix": " — conteggio locale, nessun invio.",
  "conversionCoverageGaps": "{gaps} carenze di copertura",
  "conversionSampleTitle": "Esempio di ottimizzazione",
  "conversionSampleBefore": "Prima",
  "conversionSampleAfter": "Dopo l'ottimizzazione",
  "conversionSampleCounts": "{open} elementi da assegnare · {conflicts} conflitti",
  "conversionAxisLabels": "Lun 8:00|Lun 12:00|Lun 16:00|Mar 8:00",
  "conversionSentTitle": "Dati per un'ottimizzazione reale",
  "conversionSentWork": "Attività: orari, requisiti e ID dell'assegnatario",
  "conversionSentPeople": "Persone: ID risorsa, competenze, disponibilità, ore e tariffe",
  "conversionSentNothingElse": "Nient'altro: niente nomi, note, contatti o record non pertinenti",
  "conversionInspect": "Vedi i dati esatti",
  "conversionPayloadNote": "Questo JSON esatto. Nessun invio prima del collegamento.",
  "conversionLockLine": "Gratis. Senza carta. Nessun invio prima del collegamento. L'esempio non modifica mai i tuoi turni.",
  "conversionAllClear": "Nessuna segnalazione nei dati attuali. Conteggio locale, nessun invio.",
  "conversionNotNow": "Non ora",
  "conversionConnect": "Prova gratis",
  "conversionLearnMore": "Scopri di più",
  "menuAssign": "Assegna personale…",
  "menuUnschedule": "Rimuovi assegnazione",
  "unscheduleConfirmTitle": "Rimuovi assegnazione",
  "unscheduleConfirmMessage": "Rimuovere l'assegnazione di {title}? Il turno mantiene l'orario e torna in Non pianificati per riassegnarlo.",
  "unscheduleConfirmAction": "Rimuovi assegnazione",
  "unscheduledLaneLabel": "Non pianificati · {count}",
  "assignTitle": "Assegna personale",
  "assignBestOptions": "Opzioni migliori",
  "assignNotAvailable": "Non disponibile",
  "assignShowEveryone": "Mostra tutti ({count})",
  "assignSearchPlaceholder": "Cerca personale",
  "assignHoursLeft": "{left} h residue su {capacity} h",
  "assignReasonMissingSkill": "Competenza mancante: {tag}",
  "assignReasonUnavailable": "Non disponibile {range}",
  "assignReasonBusy": "Già al lavoro {range}",
  "assignReasonHours": "Supererebbe {capacity} h",
  "assignEmpty": "Nessuna persona trovata.",
  "assignAction": "Assegna a {name}",
  "monthMore": "+{count} altri",
  "monthsLong": "gennaio|febbraio|marzo|aprile|maggio|giugno|luglio|agosto|settembre|ottobre|novembre|dicembre",
  "monthsShort": "gen|feb|mar|apr|mag|giu|lug|ago|set|ott|nov|dic",
  "moveAmount": "Quantità",
  "moveDialogTitle": "Sposta a",
  "moveDirection": "Direzione",
  "moveUnit": "Unità",
  "name": "Nome",
  "needsCover": "Da coprire",
  "newEvent": "Nuovo evento",
  "next": "Avanti",
  "optionMissingSkills": "manca {skills}",
  "optionSkillMismatch": "{count}/{total} competenze mancanti",
  "noticeBlocked": "Bloccato: {reason}",
  "noticeWarning": "Nota: {reason}",
  "pinnedNotice": "Fissato. Sblocca per modificare.",
  "previous": "Indietro",
  "reassignDialogTitle": "Riassegna a",
  "modeOperate": "Gestisci",
  "modePlan": "Pianifica",
  "optimizePeriod": "Ottimizza i turni",
  "periodNext": "Periodo successivo",
  "periodOf": "giorno {day} di {days}",
  "planningPeriodLabel": "Periodo di pianificazione",
  "publishAction": "Pubblica",
  "publishBlockedSequential": "Pubblica prima i turni precedenti.",
  "publishConfirmMessage": "Pubblicare {range}? Il personale vedrà i turni e le modifiche successive saranno tracciate.",
  "publishConfirmTitle": "Pubblica i turni",
  "publishByLine": "Pubblica entro il {date}",
  "publishOverdueDay": "{days} giorno di ritardo",
  "publishOverdueDays": "{days} giorni di ritardo",
  "publishedLine": "Pubblicato il {date}",
  "railAddRoster": "Aggiungi turni",
  "railLabel": "Orizzonte di pianificazione",
  "railScrollBack": "Scorri indietro",
  "railScrollForward": "Scorri avanti",
  "redo": "Ripeti",
  "rosterActions": "Azioni sui turni",
  "rosterCardLabel": "Turni {range}",
  "rosterDeleteConfirmMessage": "Eliminare {range}? I turni generati non assegnati saranno rimossi; quelli assegnati resteranno.",
  "rosterDeleteConfirmTitle": "Elimina i turni",
  "rosterDeleted": "Turni {range} eliminati: {count} turni non assegnati rimossi",
  "rosterGenerate": "Genera turni",
  "rosterProgressFull": "Tutto pianificato",
  "rosterProgressNotStarted": "Non iniziato",
  "rosterPercentScheduled": "{percent}% pianificato",
  "scopeNotice": "Nulla cambia fuori da questi turni.",
  "statusDraft": "Bozza",
  "statusLocked": "Bloccato",
  "statusPublished": "Pubblicato",
  "periodPrevious": "Periodo precedente",
  "proposalApply": "Applica",
  "proposalAppliedMany": "{count} suggerimenti applicati",
  "proposalAppliedOne": "1 suggerimento applicato",
  "proposalBlocked": "{count} bloccati",
  "proposalChanges": "{count} modifiche proposte",
  "proposalNotes": "{count} note",
  "proposalDiscard": "Scarta",
  "proposalEmpty": "Nessuna modifica proposta",
  "proposalChangeOne": "1 modifica proposta",
  "proposalDropped": "{count} scartati",
  "proposalDropChange": "Scarta modifica",
  "proposalKeepChange": "Mantieni modifica",
  "proposalReviewHint": "Proposta in esame. Applica o scarta per modificare.",
  "proposalShowCurrent": "Attuale",
  "proposalShowProposed": "Proposto",
  "proposalPanelTitle": "Modifiche proposte",
  "proposalGroupAssigned": "Assegnati ({count})",
  "proposalGroupMoved": "Spostati ({count})",
  "proposalGroupBlocked": "Bloccati ({count})",
  "proposalGroupUnassigned": "Non assegnati ({count})",
  "proposalMustBroken": "Alcune regole obbligatorie violate",
  "proposalMustKept": "Tutte le regole obbligatorie rispettate",
  "proposalOpenMany": "{count} turni non assegnati",
  "proposalOpenOne": "1 turno non assegnato",
  "proposalWas": "prima: {detail}",
  "solveQueued": "In coda…",
  "solveElapsed": "{seconds} s",
  "requiredSkills": "Competenze richieste",
  "resizeResources": "Ridimensiona colonna risorse",
  "resizeUnscheduled": "Ridimensiona pannello non pianificati",
  "resourceHeader": "Risorsa",
  "save": "Salva",
  "savedViews": "Viste",
  "start": "Inizio",
  "solve": "Ottimizza",
  "solveFailed": "Ottimizzazione fallita: {message}",
  "solveQuotaRemaining": "Restano {remaining} ottimizzazioni gratuite su {limit} oggi",
  "solveQuotaExhausted": "Ottimizzazioni gratuite di oggi esaurite. Torna domani o passa al piano illimitato.",
  "solveQuotaUpgrade": "Cambia piano",
  "resumeFinished": "Un'ottimizzazione è terminata mentre eri via.",
  "resumeRunning": "Un'ottimizzazione è in corso per questi turni.",
  "resumeChanged": "Un'ottimizzazione è terminata mentre eri via, ma i turni sono cambiati. Il risultato non è più applicabile.",
  "resumeReview": "Rivedi",
  "resumeFollow": "Segui",
  "resumeDiscard": "Scarta",
  "openChronaAccount": "Apri account Chrona",
  "solveSolving": "Ottimizzazione…",
  "timeScale": "Scala temporale",
  "timeScaleLeast": "{count} minuti – meno spazio per i dettagli",
  "timeScaleMinutes": "{count} minuti",
  "timeScaleMost": "{count} minuti – più spazio per i dettagli",
  "timeScaleShort": "{count} min",
  "timeZoneChip": "Fuso orario visualizzato",
  "timelineLabel": "Cronologia risorse",
  "today": "Oggi",
  "undo": "Annulla",
  "unpublishAction": "Ritira pubblicazione",
  "unpublishBlockedSequential": "Ritira prima la pubblicazione dei turni successivi.",
  "unpublishConfirmMessage": "Ritirare la pubblicazione di {range}? I turni tornano in bozza; la cronologia resta disponibile per le verifiche.",
  "unpublishConfirmTitle": "Ritira pubblicazione",
  "unitDays": "Giorni",
  "unitHours": "Ore",
  "unitWeeks": "Settimane",
  "unscheduledAll": "Tutti",
  "unscheduledEmpty": "Tutto coperto.",
  "unscheduledEmptyInView": "Nulla in questo periodo.",
  "unscheduledFilterLabel": "Filtra elementi non pianificati",
  "unscheduledInView": "Nella vista",
  "unscheduledTitle": "Non pianificati",
  "weekdaysShort": "dom|lun|mar|mer|gio|ven|sab",
  "nextMonth": "Mese successivo",
  "previousMonth": "Mese precedente",
  "schedulerSettings": "Impostazioni del calendario",
  "weekdaysLong": "domenica|lunedì|martedì|mercoledì|giovedì|venerdì|sabato",
  "noDate": "Senza data"
};
