import type { SchedulerStrings } from "../src/stringResources";

/** Compact portuguese labels; keep placeholders and date-name order intact. */
export const portugueseStrings: SchedulerStrings = {
  "agendaEmpty": "Nada agendado neste período.",
  "apply": "Aplicar",
  "assignedTo": "Atribuído a",
  "unassigned": "Sem atribuição",
  "cancel": "Cancelar",
  "close": "Fechar",
  "delete": "Eliminar",
  "deleteConfirmAction": "Eliminar",
  "deleteConfirmCount": "Eliminar {count} itens? Esta ação é irreversível.",
  "deleteConfirmMessage": "Eliminar {title}? Esta ação é irreversível.",
  "deleteConfirmTitle": "Confirmar eliminação",
  "dialogFinishAfterStart": "O fim deve ser posterior ao início.",
  "directionEarlier": "Antes",
  "directionLater": "Depois",
  "dialogNameRequired": "O nome é obrigatório.",
  "dialogBestOptions": "Melhores opções",
  "dialogNotAllowed": "Esta alteração não é permitida.",
  "dialogOtherOptions": "Outras",
  "draftItem": "Novo item",
  "duration": "Duração",
  "emptyResources": "Sem recursos. Verifique a configuração da vista.",
  "entitlementGrace": "Pagamento em atraso. Prazo até {date}",
  "entitlementLapsed": "Subscrição Chrona expirada. Otimização e geração suspensas até regularizar o pagamento.",
  "entitlementPaused": "Otimizador suspenso desde {since}. Chrona inacessível; pode continuar a agendar.",
  "entitlementPlanUsage": "Plano e uso",
  "entitlementResources": "{scheduled} de {included} recursos agendados neste período",
  "entitlementResourcesAbovePlan": "{scheduled} de {included} recursos agendados; acima do plano",
  "entitlementResourcesNoCeiling": "{scheduled} recursos agendados neste período",
  "entitlementRetry": "Tentar de novo",
  "finish": "Fim",
  "flagCauseAssigned": "atribuído",
  "flagCauseEdited": "editado",
  "flagCausePinned": "fixado",
  "flagReason": "Já não é necessário: {required} necessários, {existing} existentes. Mantido por estar {cause}.",
  "goToDate": "Ir para data",
  "interval": "Intervalo",
  "intervalDay": "Dia",
  "itemsCount": "{count} itens",
  "intervalDaySpan": "Faixa",
  "intervalMonth": "Mês",
  "intervalWeek": "Semana",
  "legendBusyElsewhere": "Ocupado noutra tarefa",
  "legendCustom": "Destacado",
  "legendHoliday": "Feriado",
  "legendNeedsCover": "Por preencher",
  "legendNonWorking": "Fora do horário",
  "legendPreferred": "Horário preferido",
  "legendUnavailable": "Indisponível",
  "legendUnpreferred": "Horário não preferido",
  "menuDeleteCount": "Eliminar {count} itens",
  "menuDuplicate": "Duplicar",
  "menuOpen": "Abrir",
  "menuOpenRecord": "Abrir registo",
  "menuPin": "Fixar",
  "menuPinCount": "Fixar {count} itens",
  "menuUnpin": "Desafixar",
  "menuUnpinCount": "Desafixar {count} itens",
  "menuMoveTo": "Mover para…",
  "menuMoveToCount": "Mover {count} itens para…",
  "menuReassign": "Reatribuir a…",
  "menuReassignCount": "Reatribuir {count} itens a…",
  "groupByLabel": "Agrupar linhas",
  "groupByNone": "Sem grupos",
  "ungrouped": "Sem grupo",
  "hideUnscheduledPanel": "Ocultar itens por agendar",
  "unscheduledToggle": "Por agendar ({count})",
  "conversionOptimize": "Otimizar",
  "conversionTitle": "Toda a escala, de uma só vez",
  "conversionPitchProblem": "Agendar um item de cada vez oculta as interações.",
  "conversionPitchMechanism": "Chrona considera toda a escala: competências, disponibilidade, horas, custos e conflitos.",
  "conversionInfoLead": "Opcional. Teste grátis.",
  "conversionInfoBody": "Ligar Chrona não altera o funcionamento do agendador.",
  "conversionClaimBase": "Trabalho atribuído. Conflitos resolvidos.",
  "conversionClaimRespected": "Critérios respeitados: {list}.",
  "capabilityAssignment": "atribuições",
  "capabilityLocks": "bloqueios",
  "capabilityRoles": "funções",
  "capabilityAvailability": "disponibilidade",
  "capabilityHours": "horas",
  "capabilityCost": "custos",
  "listAnd": "e",
  "solveCapabilitiesLine": "A otimizar com: {list}",
  "conversionCountsSuffix": " — contagem local, sem envio de dados.",
  "conversionCoverageGaps": "{gaps} falhas de cobertura",
  "conversionSampleTitle": "Exemplo de otimização",
  "conversionSampleBefore": "Antes",
  "conversionSampleAfter": "Após otimizar",
  "conversionSampleCounts": "{open} itens por atribuir · {conflicts} conflitos",
  "conversionAxisLabels": "Seg 8:00|Seg 12:00|Seg 16:00|Ter 8:00",
  "conversionSentTitle": "Dados de uma otimização real",
  "conversionSentWork": "Tarefas: horários, requisitos e ID da pessoa atribuída",
  "conversionSentPeople": "Pessoas: IDs, competências, disponibilidade, horas e custos horários",
  "conversionSentNothingElse": "Nada mais: sem nomes, notas, contactos ou registos não relacionados",
  "conversionInspect": "Ver dados exatos",
  "conversionPayloadNote": "Este JSON exato. Nada é enviado antes de ligar.",
  "conversionLockLine": "Grátis. Sem cartão. Nada é enviado antes de ligar. O exemplo nunca altera a sua escala.",
  "conversionAllClear": "Sem alertas nos dados atuais. Contagem local, sem envio de dados.",
  "conversionNotNow": "Agora não",
  "conversionConnect": "Testar grátis",
  "conversionLearnMore": "Saiba mais",
  "menuAssign": "Atribuir pessoal…",
  "menuUnschedule": "Desatribuir",
  "unscheduleConfirmTitle": "Desatribuir turno",
  "unscheduleConfirmMessage": "Desatribuir {title}? O turno mantém o horário e volta a Por agendar para nova atribuição.",
  "unscheduleConfirmAction": "Desatribuir",
  "unscheduledLaneLabel": "Por agendar · {count}",
  "assignTitle": "Atribuir pessoal",
  "assignBestOptions": "Melhores opções",
  "assignNotAvailable": "Indisponível",
  "assignShowEveryone": "Ver todos ({count})",
  "assignSearchPlaceholder": "Procurar pessoal",
  "assignHoursLeft": "Restam {left} h de {capacity} h",
  "assignReasonUnavailable": "Indisponível {range}",
  "assignReasonBusy": "Já trabalha {range}",
  "assignReasonHours": "Excederia {capacity} h",
  "assignEmpty": "Nenhuma pessoa encontrada.",
  "assignAction": "Atribuir a {name}",
  "monthMore": "+{count} mais",
  "monthsLong": "janeiro|fevereiro|março|abril|maio|junho|julho|agosto|setembro|outubro|novembro|dezembro",
  "monthsShort": "jan|fev|mar|abr|mai|jun|jul|ago|set|out|nov|dez",
  "moveAmount": "Quantidade",
  "moveDialogTitle": "Mover para",
  "moveDirection": "Direção",
  "moveUnit": "Unidade",
  "name": "Nome",
  "needsCover": "Por preencher",
  "newEvent": "Novo evento",
  "next": "Seguinte",
  "noticeBlocked": "Bloqueado: {reason}",
  "noticeWarning": "Nota: {reason}",
  "pinnedNotice": "Fixado. Desafixe para editar.",
  "previous": "Anterior",
  "reassignDialogTitle": "Reatribuir a",
  "periodNext": "Período seguinte",
  "periodOf": "dia {day} de {days}",
  "redo": "Refazer",
  "rosterOpenShifts": "Turnos por atribuir",
  "periodPrevious": "Período anterior",
  "proposalApply": "Aplicar",
  "proposalAppliedMany": "{count} sugestões aplicadas",
  "proposalAppliedOne": "1 sugestão aplicada",
  "proposalDiscard": "Descartar",
  "proposalEmpty": "Sem alterações propostas",
  "proposalDropped": "{count} descartados",
  "proposalDropChange": "Descartar alteração",
  "proposalKeepChange": "Manter alteração",
  "proposalKeepAll": "Manter todas",
  "proposalKeepNone": "Não manter nenhuma",
  "proposalPerPerson": "{count} alterações, resumidas por pessoa.",
  "proposalPersonShifts": "{count} turnos · {hours} h",
  "proposalPersonShiftOne": "1 turno · {hours} h",
  "proposalHeldBack": "Retidas ({count})",
  "proposalHeldBackHint": "Cada uma criaria uma dupla atribuição, por isso Aplicar não a inclui.",
  "proposalApplyAll": "Aplicar as {count}",
  "proposalApplySome": "Aplicar {kept} de {count}",
  "proposalReviewHint": "A rever proposta. Aplique ou descarte para editar.",
  "proposalShowCurrent": "Atual",
  "proposalShowProposed": "Proposto",
  "proposalHoldCompare": "Manter para comparar",
  "proposalChangesOnly": "Só alterações",
  "proposalPanelTitle": "Alterações propostas",
  "proposalPanelToggle": "Alterações propostas ({count})",
  "proposalGroupAssigned": "Atribuídos ({count})",
  "proposalGroupMoved": "Movidos ({count})",
  "proposalGroupUnassigned": "Sem atribuição ({count})",
  "proposalMustBroken": "Algumas regras obrigatórias violadas",
  "proposalMustKept": "Todas as regras obrigatórias cumpridas",
  "proposalWas": "antes: {detail}",
  "proposalTitle": "Escala proposta",
  "proposalSummaryChangeOne": "1 alteração",
  "proposalSummaryChanges": "{count} alterações",
  "proposalFilled": "{filled} de {total} turnos preenchidos",
  "scorecardLabel": "Em relação à escala atual",
  "scoreFilled": "Turnos preenchidos",
  "scoreMustBroken": "Regras obrigatórias violadas",
  "scoreNone": "Nenhuma",
  "scoreSome": "Algumas",
  "scoreNotChecked": "Não verificado",
  "scoreChanges": "Alterações",
  "scorePeople": "Pessoas afetadas",
  "scoreVsNow": "{delta} vs. atual",
  "scoreNoChange": "Inalterado",
  "scoreOfPeople": "de {count} pessoas",
  "scorecardToggle": "Indicadores",
  "scoreSearch": "Escalas testadas",
  "scoreSearchNote": "{better} melhorias · {seconds} s",
  "scoreSearchNoteOne": "1 melhoria · {seconds} s",
  "scoreSearchUnit": "versões",
  "proposalCheckFoundMany": "{count} alterações ficaram desatualizadas. Verifique-as e aplique novamente.",
  "proposalCheckFoundOne": "1 alteração ficou desatualizada. Verifique-a e aplique novamente.",
  "proposalDoubleBookingMany": "{count} duplas atribuições",
  "proposalDoubleBookingOne": "1 dupla atribuição",
  "proposalDoubleBooks": "Dupla atribuição de {person} com {title}",
  "proposalGroupOutOfDate": "Desatualizadas ({count})",
  "proposalOutOfDate": "{count} desatualizadas",
  "proposalReasonChanged": "Alterado depois de o plano ser criado",
  "proposalReasonNewShift": "{person} tem agora outro turno a esta hora",
  "proposalReasonPersonChanged": "Os dados de {person} mudaram depois de o plano ser criado",
  "proposalReasonStarted": "Já começou",
  "proposalReasonUnavailable": "{person} está agora indisponível a esta hora",
  "solvePeriodPassed": "Este período já passou",
  "solveQueued": "Em fila…",
  "solveElapsed": "{seconds} s",
  "requiredSkills": "Competências exigidas",
  "resizeResources": "Redimensionar coluna de recursos",
  "resizeUnscheduled": "Redimensionar painel por agendar",
  "resourceHeader": "Recurso",
  "save": "Guardar",
  "savedViews": "Vistas",
  "start": "Início",
  "solve": "Otimizar",
  "solveFailed": "Falha na otimização: {message}",
  "solveQuotaRemaining": "Restam {remaining} de {limit} otimizações grátis hoje",
  "solveQuotaExhausted": "Esgotou as otimizações grátis de hoje. Volte amanhã ou mude de plano para uso ilimitado.",
  "solveQuotaUpgrade": "Mudar de plano",
  "resumeFinished": "Uma otimização terminou na sua ausência.",
  "resumeRunning": "Está em curso uma otimização desta escala.",
  "resumeChanged": "Uma otimização terminou na sua ausência, mas a escala mudou. O resultado já não se aplica.",
  "resumeReview": "Rever",
  "resumeFollow": "Acompanhar",
  "resumeDiscard": "Descartar",
  "openChronaAccount": "Abrir conta Chrona",
  "solveSolving": "A otimizar…",
  "timeScale": "Escala temporal",
  "timeScaleLeast": "{count} minutos: menos espaço para detalhes",
  "timeScaleMinutes": "{count} minutos",
  "timeScaleMost": "{count} minutos: mais espaço para detalhes",
  "timeScaleShort": "{count} min",
  "timeZoneChip": "Fuso horário visível",
  "timelineLabel": "Cronologia de recursos",
  "today": "Hoje",
  "undo": "Anular",
  "unitDays": "Dias",
  "unitHours": "Horas",
  "unitWeeks": "Semanas",
  "unscheduledAll": "Todos",
  "unscheduledEmpty": "Tudo preenchido.",
  "unscheduledEmptyInView": "Nada neste período.",
  "unscheduledFilterLabel": "Filtrar itens por agendar",
  "unscheduledInView": "Na vista",
  "unscheduledTitle": "Por agendar",
  "weekdaysShort": "dom|seg|ter|qua|qui|sex|sáb",
  "nextMonth": "Mês seguinte",
  "previousMonth": "Mês anterior",
  "schedulerSettings": "Definições do agendador",
  "fullScreen": "Ecrã inteiro",
  "fullScreenExit": "Sair do ecrã inteiro",
  "weekdaysLong": "domingo|segunda-feira|terça-feira|quarta-feira|quinta-feira|sexta-feira|sábado",
  "noDate": "Sem data",
  "scoreNotCounted": "Não contado desta vez",
  "mustBreakdownTitle": "Regras obrigatórias",
  "mustRowRest": "Descanso entre turnos",
  "mustRowDaysInARow": "Dias seguidos",
  "mustRowSkills": "Competências",
  "mustRowOnLeave": "Ausente ou indisponível",
  "mustRowOther": "Outras regras obrigatórias",
  "mustKindOverlap": "Dupla atribuição",
  "mustKindMaximumHours": "Horas máx.",
  "mustKindSplitParts": "Turno repartido",
  "mustKindUnlisted": "Outras",
  "mustRowSummary": "{rule}: {now} agora, {proposed} na proposta",
  "mustRowOpen": "{rule}: {now} agora, {proposed} na proposta. Mostrar turnos",
  "mustUncheckedOne": "Não verificado para 1 pessoa",
  "mustUnchecked": "Não verificado para {count} pessoas",
  "mustNoAgreementOne": "1 pessoa não tem acordo: descanso e limites de dias não verificados.",
  "mustNoAgreement": "{count} pessoas não têm acordo: descanso e limites de dias não verificados.",
  "mustNoAgreementNobody": "Ninguém tem acordo: descanso e limites de dias não verificados.",
  "proposalMustKeptUncheckedOne": "Regras obrigatórias cumpridas · não verificado para 1 pessoa",
  "proposalMustKeptUnchecked": "Regras obrigatórias cumpridas · não verificado para {count} pessoas",
  "drillGroup": "{rule} ({count})",
  "drillMore": "e mais {count}",
  "reasonFixesRest": "Corrige o descanso de {name} ({hours} h)",
  "reasonFixesDaysInARow": "Corrige os dias seguidos de {name}",
  "reasonFixesSkill": "Corrige uma competência em falta",
  "reasonFixesMust": "Corrige uma regra obrigatória violada",
  "reasonAddsRest": "Cria um descanso curto para {name} ({hours} h)",
  "reasonAddsMust": "Viola uma regra obrigatória",
  "reasonUnpreferred": "{name} prefere não trabalhar nesse horário",
  "reasonAvoidsUnpreferred": "Evita o horário não preferido de {name}",
  "reasonFillsOpen": "Preenche um turno por atribuir",
  "reasonPersonFixesOne": "Corrige 1 violação",
  "reasonPersonFixes": "Corrige {count} violações",
  "countsOnlyNote": "Escala grande: só contagens. Os motivos não são mostrados.",
  "tryAgain": "Tentar de novo",
  "menuWhyNot": "Porque não…?",
  "whyNotPerson": "Pessoa",
  "whyNotPlaceholder": "Escreva um nome",
  "whyNotNoMatch": "Sem resultados",
  "whyNotNow": "agora {name}",
  "whyNotChecking": "A verificar {name}…",
  "whyNotVerdictMustOne": "{name} violaria 1 regra obrigatória",
  "whyNotVerdictMust": "{name} violaria {count} regras obrigatórias",
  "whyNotVerdictShould": "{name} cumpre todas as regras obrigatórias, mas encaixa pior",
  "whyNotVerdictEqual": "{name} encaixa igualmente bem.",
  "whyNotVerdictEqualReview": "{name} encaixa igualmente bem. A otimização teve de escolher.",
  "whyNotVerdictBetter": "{name} encaixa melhor.",
  "whyNotTakingOff": "{name} perde o turno",
  "whyNotPrefers": "{name} prefere trabalhar nesse horário",
  "ruleSpreadOfShifts": "Distribuição de turnos",
  "ruleMinimumHours": "Horas mínimas",
  "whyNotLessEven": "{rule}: menos equilibrada",
  "whyNotMoreEven": "{rule}: mais equilibrada",
  "whyNotWorse": "{rule}: pior",
  "whyNotBetter": "{rule}: melhor",
  "whyNotNoAgreement": "{name} não tem acordo: descanso e limites de dias não verificados.",
  "whyNotUnavailable": "Não foi possível verificar agora",
  "whyNotRetryIn": "Não foi possível verificar agora. Tente de novo dentro de {seconds} s.",
  "whyNotRosterChanged": "A escala mudou.",
  "whyNotAskAgain": "Perguntar de novo",
  "whyNotAssign": "Atribuir a {name}",
  "whyNotSwap": "Trocar {name} e {other}",
  "whyNotTakes": "{name} fica com {shift}",
  "whyNotLeftOpen": "{shift} de {name} ficaria por atribuir",
  "whyNotInReview": "Para usar {name}, descarte esta alteração e aja depois de Aplicar.",
  "scorePreferences": "Preferências cumpridas",
  "scorePreferencesValue": "{met} de {total}",
  "scorePreferencesNone": "Sem preferências registadas",
  "preferencesUnmetTitle": "Preferências não cumpridas"
};
