import type { SchedulerStrings } from "../src/stringResources";

/** Compact portuguese labels; keep placeholders and date-name order intact. */
export const portugueseStrings: SchedulerStrings = {
  "agendaEmpty": "Nada agendado neste período.",
  "apply": "Aplicar",
  "assignedTo": "Atribuído a",
  "unassigned": "Sem atribuição",
  "bandBusyElsewhere": "Ocupado noutra tarefa",
  "bandPreferred": "Preferido",
  "bandUnavailable": "Indisponível",
  "bandUnpreferred": "Não preferido",
  "cancel": "Cancelar",
  "close": "Fechar",
  "delete": "Eliminar",
  "deleteConfirmAction": "Eliminar",
  "deleteConfirmCount": "Eliminar {count} itens? Esta ação é irreversível.",
  "deleteConfirmMessage": "Eliminar {title}? Esta ação é irreversível.",
  "deleteConfirmTitle": "Confirmar eliminação",
  "dialogFinishAfterStart": "O fim deve ser posterior ao início.",
  "changesSinceMany": "{count} alterações desde",
  "changesSinceNone": "Sem alterações desde",
  "changesSinceOne": "{count} alteração desde",
  "coverage": "Cobertura",
  "currentRosterLabel": "Escala atual",
  "directionEarlier": "Antes",
  "directionLater": "Depois",
  "dialogNameRequired": "O nome é obrigatório.",
  "dialogBestOptions": "Melhores opções",
  "dialogNotAllowed": "Esta alteração não é permitida.",
  "dialogOtherOptions": "Outras",
  "draftItem": "Novo item",
  "duration": "Duração",
  "emptyResources": "Sem recursos. Verifique a configuração da vista.",
  "entitlementGrace": "Pagamento em atraso. Prazo até {date}",
  "entitlementLapsed": "Subscrição Chrona expirada. Otimização e geração suspensas até regularizar o pagamento.",
  "entitlementPaused": "Otimizador suspenso desde {since}. Chrona inacessível; pode continuar a agendar.",
  "entitlementPlanUsage": "Plano e uso",
  "entitlementResources": "{scheduled} de {included} recursos agendados neste período",
  "entitlementResourcesAbovePlan": "{scheduled} de {included} recursos agendados; acima do plano",
  "entitlementResourcesNoCeiling": "{scheduled} recursos agendados neste período",
  "entitlementRetry": "Tentar de novo",
  "finish": "Fim",
  "flagCauseAssigned": "atribuído",
  "flagCauseEdited": "editado",
  "flagCausePinned": "fixado",
  "flagReason": "Já não é necessário: {required} necessários, {existing} existentes. Mantido por estar {cause}.",
  "goToDate": "Ir para data",
  "horizonFull": "Não é possível adicionar mais escalas neste horizonte.",
  "horizonHeader": "Horizonte {range} ({days} dias)",
  "interval": "Intervalo",
  "intervalDay": "Dia",
  "itemsCount": "{count} itens",
  "intervalDaySpan": "Faixa",
  "intervalMonth": "Mês",
  "intervalWeek": "Semana",
  "legendBusyElsewhere": "Ocupado noutra tarefa",
  "legendCustom": "Destacado",
  "legendHoliday": "Feriado",
  "legendNeedsCover": "Por preencher",
  "legendNonWorking": "Fora do horário",
  "legendPreferred": "Horário preferido",
  "legendUnavailable": "Indisponível",
  "legendUnpreferred": "Horário não preferido",
  "menuDeleteCount": "Eliminar {count} itens",
  "menuDuplicate": "Duplicar",
  "menuOpen": "Abrir",
  "menuOpenRecord": "Abrir registo",
  "menuPin": "Fixar",
  "menuPinCount": "Fixar {count} itens",
  "menuUnpin": "Desafixar",
  "menuUnpinCount": "Desafixar {count} itens",
  "menuMoveTo": "Mover para…",
  "menuMoveToCount": "Mover {count} itens para…",
  "menuReassign": "Reatribuir a…",
  "menuReassignCount": "Reatribuir {count} itens a…",
  "groupByLabel": "Agrupar linhas",
  "groupByNone": "Sem grupos",
  "ungrouped": "Sem grupo",
  "hideUnscheduledPanel": "Ocultar itens por agendar",
  "unscheduledToggle": "Por agendar ({count})",
  "conversionOptimize": "Otimizar",
  "conversionTitle": "Toda a escala, de uma só vez",
  "conversionPitchProblem": "Agendar um item de cada vez oculta as interações.",
  "conversionPitchMechanism": "Chrona considera toda a escala: competências, disponibilidade, horas, custos e conflitos.",
  "conversionInfoLead": "Opcional. Teste grátis.",
  "conversionInfoBody": "Ligar Chrona não altera o funcionamento do agendador.",
  "conversionClaimBase": "Trabalho atribuído. Conflitos resolvidos.",
  "conversionClaimRespected": "Critérios respeitados: {list}.",
  "capabilityAssignment": "atribuições",
  "capabilityLocks": "bloqueios",
  "capabilityRoles": "funções",
  "capabilityAvailability": "disponibilidade",
  "capabilityHours": "horas",
  "capabilityCost": "custos",
  "listAnd": "e",
  "solveCapabilitiesLine": "A otimizar com: {list}",
  "generate": "Gerar",
  "generateWindowTitle": "Gerar a partir de modelos",
  "generateWindowIntro": "Cria itens por atribuir a partir dos modelos neste período. Ao repetir, remove o excedente intacto e mantém e sinaliza itens editados ou atribuídos.",
  "generateWindowFrom": "De",
  "generateWindowTo": "Até",
  "generateWindowAction": "Gerar",
  "conversionCountsSuffix": " — contagem local, sem envio de dados.",
  "conversionCoverageGaps": "{gaps} falhas de cobertura",
  "conversionSampleTitle": "Exemplo de otimização",
  "conversionSampleBefore": "Antes",
  "conversionSampleAfter": "Após otimizar",
  "conversionSampleCounts": "{open} itens por atribuir · {conflicts} conflitos",
  "conversionAxisLabels": "Seg 8:00|Seg 12:00|Seg 16:00|Ter 8:00",
  "conversionSentTitle": "Dados de uma otimização real",
  "conversionSentWork": "Tarefas: horários, requisitos e ID da pessoa atribuída",
  "conversionSentPeople": "Pessoas: IDs, competências, disponibilidade, horas e custos horários",
  "conversionSentNothingElse": "Nada mais: sem nomes, notas, contactos ou registos não relacionados",
  "conversionInspect": "Ver dados exatos",
  "conversionPayloadNote": "Este JSON exato. Nada é enviado antes de ligar.",
  "conversionLockLine": "Grátis. Sem cartão. Nada é enviado antes de ligar. O exemplo nunca altera a sua escala.",
  "conversionAllClear": "Sem alertas nos dados atuais. Contagem local, sem envio de dados.",
  "conversionNotNow": "Agora não",
  "conversionConnect": "Testar grátis",
  "conversionLearnMore": "Saiba mais",
  "menuAssign": "Atribuir pessoal…",
  "menuUnschedule": "Desatribuir",
  "unscheduleConfirmTitle": "Desatribuir turno",
  "unscheduleConfirmMessage": "Desatribuir {title}? O turno mantém o horário e volta a Por agendar para nova atribuição.",
  "unscheduleConfirmAction": "Desatribuir",
  "unscheduledLaneLabel": "Por agendar · {count}",
  "assignTitle": "Atribuir pessoal",
  "assignBestOptions": "Melhores opções",
  "assignNotAvailable": "Indisponível",
  "assignShowEveryone": "Ver todos ({count})",
  "assignSearchPlaceholder": "Procurar pessoal",
  "assignHoursLeft": "Restam {left} h de {capacity} h",
  "assignReasonMissingSkill": "Falta competência: {tag}",
  "assignReasonUnavailable": "Indisponível {range}",
  "assignReasonBusy": "Já trabalha {range}",
  "assignReasonHours": "Excederia {capacity} h",
  "assignEmpty": "Nenhuma pessoa encontrada.",
  "assignAction": "Atribuir a {name}",
  "monthMore": "+{count} mais",
  "monthsLong": "janeiro|fevereiro|março|abril|maio|junho|julho|agosto|setembro|outubro|novembro|dezembro",
  "monthsShort": "jan|fev|mar|abr|mai|jun|jul|ago|set|out|nov|dez",
  "moveAmount": "Quantidade",
  "moveDialogTitle": "Mover para",
  "moveDirection": "Direção",
  "moveUnit": "Unidade",
  "name": "Nome",
  "needsCover": "Por preencher",
  "newEvent": "Novo evento",
  "next": "Seguinte",
  "optionMissingSkills": "falta {skills}",
  "optionSkillMismatch": "{count}/{total} competências em falta",
  "noticeBlocked": "Bloqueado: {reason}",
  "noticeWarning": "Nota: {reason}",
  "pinnedNotice": "Fixado. Desafixe para editar.",
  "previous": "Anterior",
  "reassignDialogTitle": "Reatribuir a",
  "modeOperate": "Gerir",
  "modePlan": "Planear",
  "optimizePeriod": "Otimizar esta escala",
  "periodNext": "Período seguinte",
  "periodOf": "dia {day} de {days}",
  "planningPeriodLabel": "Período de planeamento",
  "publishAction": "Publicar",
  "publishBlockedSequential": "Publique primeiro a escala anterior.",
  "publishConfirmMessage": "Publicar {range}? O pessoal verá a escala e as alterações posteriores serão registadas.",
  "publishConfirmTitle": "Publicar escala",
  "publishByLine": "Publicar até {date}",
  "publishOverdueDay": "{days} dia de atraso",
  "publishOverdueDays": "{days} dias de atraso",
  "publishedLine": "Publicado em {date}",
  "railAddRoster": "Adicionar escala",
  "railLabel": "Horizonte de planeamento",
  "railScrollBack": "Recuar",
  "railScrollForward": "Avançar",
  "redo": "Refazer",
  "rosterActions": "Ações da escala",
  "rosterCardLabel": "Escala {range}",
  "rosterDeleteConfirmMessage": "Eliminar {range}? Os turnos gerados por atribuir serão removidos; os atribuídos ficam na escala.",
  "rosterDeleteConfirmTitle": "Eliminar escala",
  "rosterDeleted": "Escala {range} eliminada: {count} turnos por atribuir removidos",
  "rosterGenerate": "Gerar turnos",
  "rosterProgressFull": "Tudo agendado",
  "rosterProgressNotStarted": "Por iniciar",
  "rosterPercentScheduled": "{percent}% agendado",
  "scopeNotice": "Nada muda fora desta escala.",
  "statusDraft": "Rascunho",
  "statusLocked": "Bloqueado",
  "statusPublished": "Publicado",
  "periodPrevious": "Período anterior",
  "proposalApply": "Aplicar",
  "proposalAppliedMany": "{count} sugestões aplicadas",
  "proposalAppliedOne": "1 sugestão aplicada",
  "proposalBlocked": "{count} bloqueados",
  "proposalChanges": "{count} alterações propostas",
  "proposalNotes": "{count} notas",
  "proposalDiscard": "Descartar",
  "proposalEmpty": "Sem alterações propostas",
  "proposalChangeOne": "1 alteração proposta",
  "proposalDropped": "{count} descartados",
  "proposalDropChange": "Descartar alteração",
  "proposalKeepChange": "Manter alteração",
  "proposalReviewHint": "A rever proposta. Aplique ou descarte para editar.",
  "proposalShowCurrent": "Atual",
  "proposalShowProposed": "Proposto",
  "proposalPanelTitle": "Alterações propostas",
  "proposalGroupAssigned": "Atribuídos ({count})",
  "proposalGroupMoved": "Movidos ({count})",
  "proposalGroupBlocked": "Bloqueados ({count})",
  "proposalGroupUnassigned": "Sem atribuição ({count})",
  "proposalMustBroken": "Algumas regras obrigatórias violadas",
  "proposalMustKept": "Todas as regras obrigatórias cumpridas",
  "proposalOpenMany": "{count} turnos por atribuir",
  "proposalOpenOne": "1 turno por atribuir",
  "proposalWas": "antes: {detail}",
  "solveQueued": "Em fila…",
  "solveElapsed": "{seconds} s",
  "requiredSkills": "Competências exigidas",
  "resizeResources": "Redimensionar coluna de recursos",
  "resizeUnscheduled": "Redimensionar painel por agendar",
  "resourceHeader": "Recurso",
  "save": "Guardar",
  "savedViews": "Vistas",
  "start": "Início",
  "solve": "Otimizar",
  "solveFailed": "Falha na otimização: {message}",
  "solveQuotaRemaining": "Restam {remaining} de {limit} otimizações grátis hoje",
  "solveQuotaExhausted": "Esgotou as otimizações grátis de hoje. Volte amanhã ou mude de plano para uso ilimitado.",
  "solveQuotaUpgrade": "Mudar de plano",
  "resumeFinished": "Uma otimização terminou na sua ausência.",
  "resumeRunning": "Está em curso uma otimização desta escala.",
  "resumeChanged": "Uma otimização terminou na sua ausência, mas a escala mudou. O resultado já não se aplica.",
  "resumeReview": "Rever",
  "resumeFollow": "Acompanhar",
  "resumeDiscard": "Descartar",
  "openChronaAccount": "Abrir conta Chrona",
  "solveSolving": "A otimizar…",
  "timeScale": "Escala temporal",
  "timeScaleLeast": "{count} minutos: menos espaço para detalhes",
  "timeScaleMinutes": "{count} minutos",
  "timeScaleMost": "{count} minutos: mais espaço para detalhes",
  "timeScaleShort": "{count} min",
  "timeZoneChip": "Fuso horário visível",
  "timelineLabel": "Cronologia de recursos",
  "today": "Hoje",
  "undo": "Anular",
  "unpublishAction": "Retirar publicação",
  "unpublishBlockedSequential": "Retire primeiro a publicação da escala seguinte.",
  "unpublishConfirmMessage": "Retirar a publicação de {range}? A escala volta a rascunho; o histórico fica guardado para auditoria.",
  "unpublishConfirmTitle": "Retirar publicação",
  "unitDays": "Dias",
  "unitHours": "Horas",
  "unitWeeks": "Semanas",
  "unscheduledAll": "Todos",
  "unscheduledEmpty": "Tudo preenchido.",
  "unscheduledEmptyInView": "Nada neste período.",
  "unscheduledFilterLabel": "Filtrar itens por agendar",
  "unscheduledInView": "Na vista",
  "unscheduledTitle": "Por agendar",
  "weekdaysShort": "dom|seg|ter|qua|qui|sex|sáb",
  "nextMonth": "Mês seguinte",
  "previousMonth": "Mês anterior",
  "schedulerSettings": "Definições do agendador",
  "weekdaysLong": "domingo|segunda-feira|terça-feira|quarta-feira|quinta-feira|sexta-feira|sábado",
  "noDate": "Sem data"
};
