import type { SchedulerStrings } from "../src/stringResources";

/** Compact spanish labels; keep placeholders and date-name order intact. */
export const spanishStrings: SchedulerStrings = {
  "agendaEmpty": "Nada programado en este periodo.",
  "apply": "Aplicar",
  "assignedTo": "Asignado a",
  "unassigned": "Sin asignar",
  "cancel": "Cancelar",
  "close": "Cerrar",
  "delete": "Eliminar",
  "deleteConfirmAction": "Eliminar",
  "deleteConfirmCount": "¿Eliminar {count} elementos? No se puede deshacer.",
  "deleteConfirmMessage": "¿Eliminar {title}? No se puede deshacer.",
  "deleteConfirmTitle": "Confirmar eliminación",
  "dialogFinishAfterStart": "El fin debe ser posterior al inicio.",
  "directionEarlier": "Antes",
  "directionLater": "Después",
  "dialogNameRequired": "El nombre es obligatorio.",
  "dialogBestOptions": "Mejores opciones",
  "dialogNotAllowed": "Este cambio no está permitido.",
  "dialogOtherOptions": "Otras",
  "draftItem": "Nuevo elemento",
  "duration": "Duración",
  "emptyResources": "No hay recursos. Revisa la configuración de la vista.",
  "entitlementGrace": "Pago vencido. Plazo hasta {date}",
  "entitlementLapsed": "Suscripción de Chrona vencida. Optimización y generación en pausa hasta resolver el pago.",
  "entitlementPaused": "Optimizador en pausa desde {since}. Chrona no responde; puedes seguir planificando.",
  "entitlementPlanUsage": "Plan y uso",
  "entitlementResources": "{scheduled} de {included} recursos programados este periodo",
  "entitlementResourcesAbovePlan": "{scheduled} de {included} recursos programados; plan superado",
  "entitlementResourcesNoCeiling": "{scheduled} recursos programados este periodo",
  "entitlementRetry": "Reintentar",
  "finish": "Fin",
  "flagCauseAssigned": "asignado",
  "flagCauseEdited": "editado",
  "flagCausePinned": "fijado",
  "flagReason": "Ya no se necesita: {required} requeridos, {existing} existentes. Se conserva por estar {cause}.",
  "goToDate": "Ir a fecha",
  "interval": "Intervalo",
  "intervalDay": "Día",
  "itemsCount": "{count} elementos",
  "intervalDaySpan": "Tramo",
  "intervalMonth": "Mes",
  "intervalWeek": "Semana",
  "legendBusyElsewhere": "Ocupado en otra tarea",
  "legendCustom": "Destacado",
  "legendHoliday": "Festivo",
  "legendNeedsCover": "Sin cubrir",
  "legendNonWorking": "Fuera de jornada",
  "legendPreferred": "Horario preferido",
  "legendUnavailable": "No disponible",
  "legendUnpreferred": "Horario no preferido",
  "menuDeleteCount": "Eliminar {count} elementos",
  "menuDuplicate": "Duplicar",
  "menuOpen": "Abrir",
  "menuOpenRecord": "Abrir registro",
  "menuPin": "Fijar",
  "menuPinCount": "Fijar {count} elementos",
  "menuUnpin": "Desfijar",
  "menuUnpinCount": "Desfijar {count} elementos",
  "menuMoveTo": "Mover a…",
  "menuMoveToCount": "Mover {count} elementos a…",
  "menuReassign": "Reasignar a…",
  "menuReassignCount": "Reasignar {count} elementos a…",
  "groupByLabel": "Agrupar filas",
  "groupByNone": "Sin agrupar",
  "ungrouped": "Sin grupo",
  "hideUnscheduledPanel": "Ocultar elementos sin programar",
  "unscheduledToggle": "Sin programar ({count})",
  "conversionOptimize": "Optimizar",
  "conversionTitle": "Todo el cuadrante, de una vez",
  "conversionPitchProblem": "Planificar uno a uno oculta las interacciones.",
  "conversionPitchMechanism": "Chrona evalúa todo el cuadrante: habilidades, disponibilidad, horas, costes y conflictos.",
  "conversionInfoLead": "Opcional. Pruébalo gratis.",
  "conversionInfoBody": "Conectar Chrona no cambia cómo funciona el calendario.",
  "conversionClaimBase": "Trabajo asignado. Conflictos resueltos.",
  "conversionClaimRespected": "Se respeta: {list}.",
  "capabilityAssignment": "asignaciones",
  "capabilityLocks": "bloqueos",
  "capabilityRoles": "roles",
  "capabilityAvailability": "disponibilidad",
  "capabilityHours": "horas",
  "capabilityCost": "costes",
  "listAnd": "y",
  "solveCapabilitiesLine": "Optimizando con: {list}",
  "conversionCountsSuffix": " — recuento local, sin enviar datos.",
  "conversionCoverageGaps": "{gaps} huecos sin cubrir",
  "conversionSampleTitle": "Ejemplo de optimización",
  "conversionSampleBefore": "Antes",
  "conversionSampleAfter": "Tras optimizar",
  "conversionSampleCounts": "{open} elementos abiertos · {conflicts} conflictos",
  "conversionAxisLabels": "Lun 8:00|Lun 12:00|Lun 16:00|Mar 8:00",
  "conversionSentTitle": "Datos de una optimización real",
  "conversionSentWork": "Tareas: horarios, requisitos e ID de la persona asignada",
  "conversionSentPeople": "Personal: ID, habilidades, disponibilidad, horas y tarifas",
  "conversionSentNothingElse": "Nada más: sin nombres, notas, contactos ni registros ajenos",
  "conversionInspect": "Ver datos exactos",
  "conversionPayloadNote": "Este JSON exacto. Nada se envía hasta conectar.",
  "conversionLockLine": "Gratis. Sin tarjeta. Nada se envía hasta conectar. El ejemplo nunca cambia tu cuadrante.",
  "conversionAllClear": "Sin alertas en los datos actuales. Recuento local, sin enviar datos.",
  "conversionNotNow": "Ahora no",
  "conversionConnect": "Probar gratis",
  "conversionLearnMore": "Más información",
  "menuAssign": "Asignar personal…",
  "menuUnschedule": "Desasignar",
  "unscheduleConfirmTitle": "Desasignar turno",
  "unscheduleConfirmMessage": "¿Desasignar {title}? El turno conserva su horario y vuelve a Sin programar para reasignarlo.",
  "unscheduleConfirmAction": "Desasignar",
  "unscheduledLaneLabel": "Sin programar · {count}",
  "assignTitle": "Asignar personal",
  "assignBestOptions": "Mejores opciones",
  "assignNotAvailable": "No disponible",
  "assignShowEveryone": "Ver todos ({count})",
  "assignSearchPlaceholder": "Buscar personal",
  "assignHoursLeft": "Quedan {left} h de {capacity} h",
  "assignReasonUnavailable": "No disponible {range}",
  "assignReasonBusy": "Ya trabaja {range}",
  "assignReasonHours": "Superaría {capacity} h",
  "assignEmpty": "No hay personal coincidente.",
  "assignAction": "Asignar a {name}",
  "monthMore": "+{count} más",
  "monthsLong": "enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre",
  "monthsShort": "ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic",
  "moveAmount": "Cantidad",
  "moveDialogTitle": "Mover a",
  "moveDirection": "Dirección",
  "moveUnit": "Unidad",
  "name": "Nombre",
  "needsCover": "Sin cubrir",
  "newEvent": "Nuevo evento",
  "next": "Siguiente",
  "noticeBlocked": "Bloqueado: {reason}",
  "noticeWarning": "Nota: {reason}",
  "pinnedNotice": "Fijado. Desfija para editar.",
  "previous": "Anterior",
  "reassignDialogTitle": "Reasignar a",
  "periodNext": "Periodo siguiente",
  "periodOf": "día {day} de {days}",
  "redo": "Rehacer",
  "rosterOpenShifts": "Turnos abiertos",
  "periodPrevious": "Periodo anterior",
  "proposalApply": "Aplicar",
  "proposalAppliedMany": "{count} sugerencias aplicadas",
  "proposalAppliedOne": "1 sugerencia aplicada",
  "proposalDiscard": "Descartar",
  "proposalEmpty": "Sin cambios propuestos",
  "proposalDropped": "{count} descartados",
  "proposalDropChange": "Descartar cambio",
  "proposalKeepChange": "Conservar cambio",
  "proposalKeepAll": "Conservar todos",
  "proposalKeepNone": "No conservar ninguno",
  "proposalPerPerson": "{count} cambios, resumidos por persona.",
  "proposalPersonShifts": "{count} turnos · {hours} h",
  "proposalPersonShiftOne": "1 turno · {hours} h",
  "proposalHeldBack": "Retenidos ({count})",
  "proposalHeldBackHint": "Cada uno crearía una doble asignación, así que Aplicar lo omite.",
  "proposalApplyAll": "Aplicar los {count}",
  "proposalApplySome": "Aplicar {kept} de {count}",
  "proposalReviewHint": "Revisando propuesta. Aplica o descarta para editar.",
  "proposalShowCurrent": "Actual",
  "proposalShowProposed": "Propuesto",
  "proposalHoldCompare": "Mantén para comparar",
  "proposalChangesOnly": "Solo cambios",
  "proposalPanelTitle": "Cambios propuestos",
  "proposalPanelToggle": "Cambios propuestos ({count})",
  "proposalGroupAssigned": "Asignados ({count})",
  "proposalGroupMoved": "Movidos ({count})",
  "proposalGroupUnassigned": "Sin asignar ({count})",
  "proposalMustBroken": "Se incumplen algunas reglas obligatorias",
  "proposalMustKept": "Se cumplen todas las reglas obligatorias",
  "proposalWas": "antes: {detail}",
  "proposalTitle": "Cuadrante propuesto",
  "proposalSummaryChangeOne": "1 cambio",
  "proposalSummaryChanges": "{count} cambios",
  "proposalFilled": "{filled} de {total} turnos cubiertos",
  "scorecardLabel": "Frente al cuadrante actual",
  "scoreFilled": "Turnos cubiertos",
  "scoreMustBroken": "Reglas obligatorias incumplidas",
  "scoreNone": "Ninguna",
  "scoreSome": "Algunas",
  "scoreNotChecked": "Sin comprobar",
  "scoreChanges": "Cambios",
  "scorePeople": "Personas afectadas",
  "scoreVsNow": "{delta} vs. actual",
  "scoreNoChange": "Sin cambios",
  "scoreOfPeople": "de {count} personas",
  "scorecardToggle": "Indicadores",
  "scoreSearch": "Cuadrantes probados",
  "scoreSearchNote": "{better} mejoras · {seconds} s",
  "scoreSearchNoteOne": "1 mejora · {seconds} s",
  "scoreSearchUnit": "versiones",
  "proposalCheckFoundMany": "{count} cambios quedaron desactualizados. Revísalos y vuelve a aplicar.",
  "proposalCheckFoundOne": "1 cambio quedó desactualizado. Revísalo y vuelve a aplicar.",
  "proposalDoubleBookingMany": "{count} dobles asignaciones",
  "proposalDoubleBookingOne": "1 doble asignación",
  "proposalDoubleBooks": "Doble asignación de {person} con {title}",
  "proposalGroupOutOfDate": "Desactualizados ({count})",
  "proposalOutOfDate": "{count} desactualizados",
  "proposalReasonChanged": "Cambiado después de crear el plan",
  "proposalReasonNewShift": "{person} ahora tiene otro turno a esta hora",
  "proposalReasonPersonChanged": "Los datos de {person} cambiaron después de crear el plan",
  "proposalReasonStarted": "Ya comenzó",
  "proposalReasonUnavailable": "{person} ahora no está disponible a esta hora",
  "solvePeriodPassed": "Este período ya pasó",
  "solveQueued": "En cola…",
  "solveElapsed": "{seconds} s",
  "requiredSkills": "Habilidades requeridas",
  "resizeResources": "Redimensionar columna de recursos",
  "resizeUnscheduled": "Redimensionar panel sin programar",
  "resourceHeader": "Recurso",
  "save": "Guardar",
  "savedViews": "Vistas",
  "start": "Inicio",
  "solve": "Optimizar",
  "solveFailed": "Error al optimizar: {message}",
  "solveQuotaRemaining": "Quedan {remaining} de {limit} optimizaciones gratis hoy",
  "solveQuotaExhausted": "Agotaste las optimizaciones gratis de hoy. Vuelve mañana o mejora el plan para uso ilimitado.",
  "solveQuotaUpgrade": "Mejorar plan",
  "resumeFinished": "Una optimización terminó durante tu ausencia.",
  "resumeRunning": "Hay una optimización en curso para este cuadrante.",
  "resumeChanged": "Una optimización terminó durante tu ausencia, pero el cuadrante cambió. El resultado ya no es válido.",
  "resumeReview": "Revisar",
  "resumeFollow": "Seguir",
  "resumeDiscard": "Descartar",
  "openChronaAccount": "Abrir cuenta Chrona",
  "solveSolving": "Optimizando…",
  "timeScale": "Escala temporal",
  "timeScaleLeast": "{count} minutos: menos espacio para detalles",
  "timeScaleMinutes": "{count} minutos",
  "timeScaleMost": "{count} minutos: más espacio para detalles",
  "timeScaleShort": "{count} min",
  "timeZoneChip": "Zona horaria visible",
  "timelineLabel": "Cronología de recursos",
  "today": "Hoy",
  "undo": "Deshacer",
  "unitDays": "Días",
  "unitHours": "Horas",
  "unitWeeks": "Semanas",
  "unscheduledAll": "Todos",
  "unscheduledEmpty": "Todo cubierto.",
  "unscheduledEmptyInView": "Nada en este periodo.",
  "unscheduledFilterLabel": "Filtrar elementos sin programar",
  "unscheduledInView": "En la vista",
  "unscheduledTitle": "Sin programar",
  "weekdaysShort": "dom|lun|mar|mié|jue|vie|sáb",
  "nextMonth": "Mes siguiente",
  "previousMonth": "Mes anterior",
  "schedulerSettings": "Configuración del calendario",
  "fullScreen": "Pantalla completa",
  "fullScreenExit": "Salir de pantalla completa",
  "weekdaysLong": "domingo|lunes|martes|miércoles|jueves|viernes|sábado",
  "noDate": "Sin fecha"
};
