import type { SchedulerStrings } from "../src/stringResources";

/** Compact spanish labels; keep placeholders and date-name order intact. */
export const spanishStrings: SchedulerStrings = {
  "agendaEmpty": "Nada programado en este periodo.",
  "apply": "Aplicar",
  "assignedTo": "Asignado a",
  "unassigned": "Sin asignar",
  "bandBusyElsewhere": "Ocupado en otra tarea",
  "bandPreferred": "Preferido",
  "bandUnavailable": "No disponible",
  "bandUnpreferred": "No preferido",
  "cancel": "Cancelar",
  "close": "Cerrar",
  "delete": "Eliminar",
  "deleteConfirmAction": "Eliminar",
  "deleteConfirmCount": "¿Eliminar {count} elementos? No se puede deshacer.",
  "deleteConfirmMessage": "¿Eliminar {title}? No se puede deshacer.",
  "deleteConfirmTitle": "Confirmar eliminación",
  "dialogFinishAfterStart": "El fin debe ser posterior al inicio.",
  "changesSinceMany": "{count} cambios desde",
  "changesSinceNone": "Sin cambios desde",
  "changesSinceOne": "{count} cambio desde",
  "coverage": "Cobertura",
  "currentRosterLabel": "Cuadrante actual",
  "directionEarlier": "Antes",
  "directionLater": "Después",
  "dialogNameRequired": "El nombre es obligatorio.",
  "dialogBestOptions": "Mejores opciones",
  "dialogNotAllowed": "Este cambio no está permitido.",
  "dialogOtherOptions": "Otras",
  "draftItem": "Nuevo elemento",
  "duration": "Duración",
  "emptyResources": "No hay recursos. Revisa la configuración de la vista.",
  "entitlementGrace": "Pago vencido. Plazo hasta {date}",
  "entitlementLapsed": "Suscripción de Chrona vencida. Optimización y generación en pausa hasta resolver el pago.",
  "entitlementPaused": "Optimizador en pausa desde {since}. Chrona no responde; puedes seguir planificando.",
  "entitlementPlanUsage": "Plan y uso",
  "entitlementResources": "{scheduled} de {included} recursos programados este periodo",
  "entitlementResourcesAbovePlan": "{scheduled} de {included} recursos programados; plan superado",
  "entitlementResourcesNoCeiling": "{scheduled} recursos programados este periodo",
  "entitlementRetry": "Reintentar",
  "finish": "Fin",
  "flagCauseAssigned": "asignado",
  "flagCauseEdited": "editado",
  "flagCausePinned": "fijado",
  "flagReason": "Ya no se necesita: {required} requeridos, {existing} existentes. Se conserva por estar {cause}.",
  "goToDate": "Ir a fecha",
  "horizonFull": "No caben más cuadrantes en este horizonte.",
  "horizonHeader": "Horizonte {range} ({days} días)",
  "interval": "Intervalo",
  "intervalDay": "Día",
  "itemsCount": "{count} elementos",
  "intervalDaySpan": "Tramo",
  "intervalMonth": "Mes",
  "intervalWeek": "Semana",
  "legendBusyElsewhere": "Ocupado en otra tarea",
  "legendCustom": "Destacado",
  "legendHoliday": "Festivo",
  "legendNeedsCover": "Sin cubrir",
  "legendNonWorking": "Fuera de jornada",
  "legendPreferred": "Horario preferido",
  "legendUnavailable": "No disponible",
  "legendUnpreferred": "Horario no preferido",
  "menuDeleteCount": "Eliminar {count} elementos",
  "menuDuplicate": "Duplicar",
  "menuOpen": "Abrir",
  "menuOpenRecord": "Abrir registro",
  "menuPin": "Fijar",
  "menuPinCount": "Fijar {count} elementos",
  "menuUnpin": "Desfijar",
  "menuUnpinCount": "Desfijar {count} elementos",
  "menuMoveTo": "Mover a…",
  "menuMoveToCount": "Mover {count} elementos a…",
  "menuReassign": "Reasignar a…",
  "menuReassignCount": "Reasignar {count} elementos a…",
  "groupByLabel": "Agrupar filas",
  "groupByNone": "Sin agrupar",
  "ungrouped": "Sin grupo",
  "hideUnscheduledPanel": "Ocultar elementos sin programar",
  "unscheduledToggle": "Sin programar ({count})",
  "conversionOptimize": "Optimizar",
  "conversionTitle": "Todo el cuadrante, de una vez",
  "conversionPitchProblem": "Planificar uno a uno oculta las interacciones.",
  "conversionPitchMechanism": "Chrona evalúa todo el cuadrante: habilidades, disponibilidad, horas, costes y conflictos.",
  "conversionInfoLead": "Opcional. Pruébalo gratis.",
  "conversionInfoBody": "Conectar Chrona no cambia cómo funciona el calendario.",
  "conversionClaimBase": "Trabajo asignado. Conflictos resueltos.",
  "conversionClaimRespected": "Se respeta: {list}.",
  "capabilityAssignment": "asignaciones",
  "capabilityLocks": "bloqueos",
  "capabilityRoles": "roles",
  "capabilityAvailability": "disponibilidad",
  "capabilityHours": "horas",
  "capabilityCost": "costes",
  "listAnd": "y",
  "solveCapabilitiesLine": "Optimizando con: {list}",
  "generate": "Generar",
  "generateWindowTitle": "Generar desde plantillas",
  "generateWindowIntro": "Crea elementos abiertos desde las plantillas para este periodo. Al repetir, elimina el sobrante intacto y conserva y marca lo editado o asignado.",
  "generateWindowFrom": "Desde",
  "generateWindowTo": "Hasta",
  "generateWindowAction": "Generar",
  "conversionCountsSuffix": " — recuento local, sin enviar datos.",
  "conversionCoverageGaps": "{gaps} huecos sin cubrir",
  "conversionSampleTitle": "Ejemplo de optimización",
  "conversionSampleBefore": "Antes",
  "conversionSampleAfter": "Tras optimizar",
  "conversionSampleCounts": "{open} elementos abiertos · {conflicts} conflictos",
  "conversionAxisLabels": "Lun 8:00|Lun 12:00|Lun 16:00|Mar 8:00",
  "conversionSentTitle": "Datos de una optimización real",
  "conversionSentWork": "Tareas: horarios, requisitos e ID de la persona asignada",
  "conversionSentPeople": "Personal: ID, habilidades, disponibilidad, horas y tarifas",
  "conversionSentNothingElse": "Nada más: sin nombres, notas, contactos ni registros ajenos",
  "conversionInspect": "Ver datos exactos",
  "conversionPayloadNote": "Este JSON exacto. Nada se envía hasta conectar.",
  "conversionLockLine": "Gratis. Sin tarjeta. Nada se envía hasta conectar. El ejemplo nunca cambia tu cuadrante.",
  "conversionAllClear": "Sin alertas en los datos actuales. Recuento local, sin enviar datos.",
  "conversionNotNow": "Ahora no",
  "conversionConnect": "Probar gratis",
  "conversionLearnMore": "Más información",
  "menuAssign": "Asignar personal…",
  "menuUnschedule": "Desasignar",
  "unscheduleConfirmTitle": "Desasignar turno",
  "unscheduleConfirmMessage": "¿Desasignar {title}? El turno conserva su horario y vuelve a Sin programar para reasignarlo.",
  "unscheduleConfirmAction": "Desasignar",
  "unscheduledLaneLabel": "Sin programar · {count}",
  "assignTitle": "Asignar personal",
  "assignBestOptions": "Mejores opciones",
  "assignNotAvailable": "No disponible",
  "assignShowEveryone": "Ver todos ({count})",
  "assignSearchPlaceholder": "Buscar personal",
  "assignHoursLeft": "Quedan {left} h de {capacity} h",
  "assignReasonMissingSkill": "Falta habilidad: {tag}",
  "assignReasonUnavailable": "No disponible {range}",
  "assignReasonBusy": "Ya trabaja {range}",
  "assignReasonHours": "Superaría {capacity} h",
  "assignEmpty": "No hay personal coincidente.",
  "assignAction": "Asignar a {name}",
  "monthMore": "+{count} más",
  "monthsLong": "enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre",
  "monthsShort": "ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic",
  "moveAmount": "Cantidad",
  "moveDialogTitle": "Mover a",
  "moveDirection": "Dirección",
  "moveUnit": "Unidad",
  "name": "Nombre",
  "needsCover": "Sin cubrir",
  "newEvent": "Nuevo evento",
  "next": "Siguiente",
  "optionMissingSkills": "falta {skills}",
  "optionSkillMismatch": "{count}/{total} habilidades sin cumplir",
  "noticeBlocked": "Bloqueado: {reason}",
  "noticeWarning": "Nota: {reason}",
  "pinnedNotice": "Fijado. Desfija para editar.",
  "previous": "Anterior",
  "reassignDialogTitle": "Reasignar a",
  "modeOperate": "Gestionar",
  "modePlan": "Planificar",
  "optimizePeriod": "Optimizar cuadrante",
  "periodNext": "Periodo siguiente",
  "periodOf": "día {day} de {days}",
  "planningPeriodLabel": "Periodo de planificación",
  "publishAction": "Publicar",
  "publishBlockedSequential": "Publica primero el cuadrante anterior.",
  "publishConfirmMessage": "¿Publicar {range}? El personal verá el cuadrante y se registrarán los cambios posteriores.",
  "publishConfirmTitle": "Publicar cuadrante",
  "publishByLine": "Publicar antes del {date}",
  "publishOverdueDay": "{days} día de retraso",
  "publishOverdueDays": "{days} días de retraso",
  "publishedLine": "Publicado el {date}",
  "railAddRoster": "Añadir cuadrante",
  "railLabel": "Horizonte de planificación",
  "railScrollBack": "Desplazar atrás",
  "railScrollForward": "Desplazar adelante",
  "redo": "Rehacer",
  "rosterActions": "Acciones del cuadrante",
  "rosterCardLabel": "Cuadrante {range}",
  "rosterDeleteConfirmMessage": "¿Eliminar {range}? Se borrarán los turnos generados sin asignar; los asignados se conservarán.",
  "rosterDeleteConfirmTitle": "Eliminar cuadrante",
  "rosterDeleted": "Cuadrante {range} eliminado: {count} turnos abiertos borrados",
  "rosterGenerate": "Generar turnos",
  "rosterProgressFull": "Todo programado",
  "rosterProgressNotStarted": "Sin empezar",
  "rosterPercentScheduled": "{percent}% programado",
  "scopeNotice": "No cambia nada fuera de este cuadrante.",
  "statusDraft": "Borrador",
  "statusLocked": "Bloqueado",
  "statusPublished": "Publicado",
  "periodPrevious": "Periodo anterior",
  "proposalApply": "Aplicar",
  "proposalAppliedMany": "{count} sugerencias aplicadas",
  "proposalAppliedOne": "1 sugerencia aplicada",
  "proposalBlocked": "{count} bloqueados",
  "proposalChanges": "{count} cambios propuestos",
  "proposalNotes": "{count} notas",
  "proposalDiscard": "Descartar",
  "proposalEmpty": "Sin cambios propuestos",
  "proposalChangeOne": "1 cambio propuesto",
  "proposalDropped": "{count} descartados",
  "proposalDropChange": "Descartar cambio",
  "proposalKeepChange": "Conservar cambio",
  "proposalReviewHint": "Revisando propuesta. Aplica o descarta para editar.",
  "proposalShowCurrent": "Actual",
  "proposalShowProposed": "Propuesto",
  "proposalPanelTitle": "Cambios propuestos",
  "proposalGroupAssigned": "Asignados ({count})",
  "proposalGroupMoved": "Movidos ({count})",
  "proposalGroupBlocked": "Bloqueados ({count})",
  "proposalGroupUnassigned": "Sin asignar ({count})",
  "proposalMustBroken": "Se incumplen algunas reglas obligatorias",
  "proposalMustKept": "Se cumplen todas las reglas obligatorias",
  "proposalOpenMany": "{count} turnos abiertos",
  "proposalOpenOne": "1 turno abierto",
  "proposalWas": "antes: {detail}",
  "solveQueued": "En cola…",
  "solveElapsed": "{seconds} s",
  "requiredSkills": "Habilidades requeridas",
  "resizeResources": "Redimensionar columna de recursos",
  "resizeUnscheduled": "Redimensionar panel sin programar",
  "resourceHeader": "Recurso",
  "save": "Guardar",
  "savedViews": "Vistas",
  "start": "Inicio",
  "solve": "Optimizar",
  "solveFailed": "Error al optimizar: {message}",
  "solveQuotaRemaining": "Quedan {remaining} de {limit} optimizaciones gratis hoy",
  "solveQuotaExhausted": "Agotaste las optimizaciones gratis de hoy. Vuelve mañana o mejora el plan para uso ilimitado.",
  "solveQuotaUpgrade": "Mejorar plan",
  "resumeFinished": "Una optimización terminó durante tu ausencia.",
  "resumeRunning": "Hay una optimización en curso para este cuadrante.",
  "resumeChanged": "Una optimización terminó durante tu ausencia, pero el cuadrante cambió. El resultado ya no es válido.",
  "resumeReview": "Revisar",
  "resumeFollow": "Seguir",
  "resumeDiscard": "Descartar",
  "openChronaAccount": "Abrir cuenta Chrona",
  "solveSolving": "Optimizando…",
  "timeScale": "Escala temporal",
  "timeScaleLeast": "{count} minutos: menos espacio para detalles",
  "timeScaleMinutes": "{count} minutos",
  "timeScaleMost": "{count} minutos: más espacio para detalles",
  "timeScaleShort": "{count} min",
  "timeZoneChip": "Zona horaria visible",
  "timelineLabel": "Cronología de recursos",
  "today": "Hoy",
  "undo": "Deshacer",
  "unpublishAction": "Retirar publicación",
  "unpublishBlockedSequential": "Retira primero el cuadrante siguiente.",
  "unpublishConfirmMessage": "¿Retirar {range}? El cuadrante vuelve a borrador y se conserva el historial para auditoría.",
  "unpublishConfirmTitle": "Retirar cuadrante",
  "unitDays": "Días",
  "unitHours": "Horas",
  "unitWeeks": "Semanas",
  "unscheduledAll": "Todos",
  "unscheduledEmpty": "Todo cubierto.",
  "unscheduledEmptyInView": "Nada en este periodo.",
  "unscheduledFilterLabel": "Filtrar elementos sin programar",
  "unscheduledInView": "En la vista",
  "unscheduledTitle": "Sin programar",
  "weekdaysShort": "dom|lun|mar|mié|jue|vie|sáb",
  "nextMonth": "Mes siguiente",
  "previousMonth": "Mes anterior",
  "schedulerSettings": "Configuración del calendario",
  "weekdaysLong": "domingo|lunes|martes|miércoles|jueves|viernes|sábado",
  "noDate": "Sin fecha"
};
